// SPDX-License-Identifier: MPL-2.0

//! `Action` — the abstract user-action vocabulary the event loop
//! dispatches on. New keyboard interactions go here, then add a
//! matching `KeybindConfig` field + default + binding-string list.

use serde::{Deserialize, Serialize};
use strum_macros::{EnumDiscriminants, EnumIter};

use super::context::InputContext;

// ── Action payload enums ─────────────────────────────────────────
//
// Typed discriminators for the parametric Action variants whose
// underlying console verb fans across a small fixed set of axes.
// Promoting these into the variant payload (instead of one Action
// variant per axis) keeps the dispatcher's match arm exhaustive
// without a `_ => log::error!(...)` "fan-out missed inner-match"
// guard, and eliminates the `set_color_bg / _text / _border`-style
// listing tax across `KeybindConfig`, `is_destructive`,
// `wasm_compatibility`, and `context`.
//
// Each carries a kv-key string at the boundary so the verb-core's
// existing `apply_kvs`-style trait dispatch reaches the same code
// path the typed `bg|text|border` console kv would have hit.

/// Which color axis a [`Action::SetColor`] targets. Mirrors the
/// `bg|text|border` kv key on the `color` console verb.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ColorAxis {
    Bg,
    Text,
    Border,
}

impl ColorAxis {
    /// kv-key string the `color` verb-core accepts.
    pub fn as_kv_key(self) -> &'static str {
        match self {
            ColorAxis::Bg => "bg",
            ColorAxis::Text => "text",
            ColorAxis::Border => "border",
        }
    }
}

/// Which font slot a [`Action::SetFont`] targets. Mirrors the
/// `size|min|max` kv key on the `font` console verb. Family
/// (`SetFontFamily`) lives on its own Action because the verb
/// dispatches it through a different code path.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FontSlot {
    Size,
    Min,
    Max,
}

impl FontSlot {
    /// kv-key string the `font` verb-core accepts.
    pub fn as_kv_key(self) -> &'static str {
        match self {
            FontSlot::Size => "size",
            FontSlot::Min => "min",
            FontSlot::Max => "max",
        }
    }
}

/// Which zoom bound a [`Action::SetZoom`] targets. Mirrors the
/// `min|max` kv key on the `zoom` console verb. Clearing both at
/// once lives on its own [`Action::ClearZoom`] variant — the
/// verb-core takes a `(min, max)` pair where each half is an
/// `OptionEdit<f32>`, and `Clear/Clear` is a meaningfully distinct
/// operation from `Keep/Keep`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ZoomBound {
    Min,
    Max,
}

impl ZoomBound {
    /// kv-key string the `zoom` verb-core accepts.
    pub fn as_kv_key(self) -> &'static str {
        match self {
            ZoomBound::Min => "min",
            ZoomBound::Max => "max",
        }
    }
}

/// High-level user actions that can be bound to keys. Add a new variant
/// here when a new keyboard interaction is introduced, extend
/// `KeybindConfig` with a matching field + default, and handle the variant
/// in the event loop.
///
/// `Serialize` / `Deserialize` are derived so macros can carry actions
/// in their JSON payload — see `crate::application::macros::MacroStep`.
///
/// `#[non_exhaustive]` because new variants need to be reviewed
/// against the macro privilege gate
/// (`MacroSource::allows_action`) before they ship — the gate uses
/// a denylist of destructive Actions, and a new I/O / clipboard /
/// document-lifecycle variant added without updating the denylist
/// would silently bypass the gate from non-User macro tiers. The
/// `#[non_exhaustive]` is the structural signal that "review the
/// gate when extending."
/// Some variants carry payload (e.g. `String` paths, kv-shaped
/// `(field, value)` tuples) so `Copy` is impossible — payload-bearing
/// variants are cloned at lookup time in
/// [`super::resolved::ResolvedKeybinds::action_for_context`]. Each
/// keypress allocates one short string per `String`-payload variant
/// (two for `SetEdgeAnchor` / `SetEdgeCap` / `SetBorderField`). For
/// the typical interactive cadence (≤10 keypresses/sec) the cost is
/// inconsequential; for a synthetic load of macros firing thousands
/// of `Action`s/sec, switch the lookup to return `&Action` and clone
/// at the dispatch boundary, or wrap payload strings in `Arc<str>`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, EnumDiscriminants)]
#[strum_discriminants(
    name(ActionKind),
    derive(Hash, EnumIter),
    doc = "Variant-kind mirror of [`Action`] without payloads. Generated by \
           strum's `EnumDiscriminants`. Used by the classifier methods \
           ([`is_destructive`](Self::is_destructive), \
           [`context`](Self::context), \
           [`wasm_compatibility`](Self::wasm_compatibility)) so the \
           classification matches need not destructure payloads, and by \
           tests that need to iterate every variant via `ActionKind::iter()`. \
           `&Action` and `Action` both `into()` an `ActionKind` (auto-derived)."
)]
#[non_exhaustive]
pub enum Action {
    // ── Document-level (global) ──────────────────────────────────
    /// Undo the last action on the document.
    Undo,
    /// Enter reparent mode for the currently selected nodes.
    EnterReparentMode,
    /// Enter connect mode for the currently selected node.
    EnterConnectMode,
    /// Confirm a reparent operation by clicking on a target node
    /// (or empty canvas to promote sources to root). Sources come
    /// from `AppMode::Reparent { sources }`; the payload carries
    /// the target node id (`None` for empty-canvas → root).
    /// NativeOnly: depends on `AppMode`, which doesn't exist on
    /// WASM. Classified `is_destructive = true` so the privilege
    /// gate (`MacroSource::allows_action`) denylists non-User
    /// macro tiers; the arm body's `mem::replace(.., Normal)` is
    /// an additional runtime guard (stale fire outside Reparent
    /// mode is a no-op).
    ReparentToTarget(Option<String>),
    /// Confirm a connect operation by clicking on a target node
    /// (or empty canvas to exit Connect mode without creating an
    /// edge). Source comes from `AppMode::Connect { source }`; the
    /// payload carries the target node id (`None` for empty-canvas
    /// → mode-exit only, mirroring `ReparentToTarget`'s shape).
    /// NativeOnly + `is_destructive = true` per the same reasoning
    /// as `ReparentToTarget`.
    ConnectToTarget(Option<String>),
    /// Delete the current selection (currently: selected edge).
    DeleteSelection,
    /// Cancel the current mode (reparent / connect).
    CancelMode,
    /// Create a new unattached (orphan) node at the cursor position.
    CreateOrphanNode,
    /// Detach every currently selected node from its parent.
    OrphanSelection,
    /// Open the inline text editor on the currently selected single node
    /// with the node's existing text, cursor at end.
    EditSelection,
    /// Same as `EditSelection` but opens the editor with an empty buffer.
    EditSelectionClean,
    /// Open (or toggle) the CLI console.
    OpenConsole,
    /// Save the currently-open mindmap document to its bound file path.
    SaveDocument,
    /// Copy the focused component's clipboard representation.
    /// **WASM:** the underlying `clipboard::write_clipboard` is a
    /// log-and-no-op stub today (async-clipboard integration
    /// pending). The Action is classified `Compatible` because it
    /// doesn't crash, but the user-visible behaviour is "nothing
    /// happens." Tracked in `WASM_CONVERGENCE.md`.
    Copy,
    /// Paste the system clipboard's text content into the focused component.
    /// **WASM:** same stub posture as `Copy` — `read_clipboard`
    /// returns `None`.
    Paste,
    /// Cut: copy then clear the focused component's clipboard representation.
    /// **WASM:** same stub posture as `Copy`.
    Cut,

    // ── Console ──────────────────────────────────────────────────
    /// Close the console (two-tier: dismiss popup first, then close).
    ConsoleClose,
    /// Submit the current console input line for execution.
    ConsoleSubmit,
    /// Cycle tab completions.
    ConsoleTabComplete,
    /// Walk history backward / navigate completion popup upward.
    ConsoleHistoryUp,
    /// Walk history forward / navigate completion popup downward.
    ConsoleHistoryDown,
    /// Move cursor one grapheme left.
    ConsoleCursorLeft,
    /// Move cursor one grapheme right.
    ConsoleCursorRight,
    /// Move cursor to start of input.
    ConsoleCursorHome,
    /// Move cursor to end of input.
    ConsoleCursorEnd,
    /// Delete grapheme before cursor.
    ConsoleDeleteBack,
    /// Delete grapheme after cursor.
    ConsoleDeleteForward,
    /// Insert a literal space (winit delivers Space as Named, not Character).
    ConsoleInsertSpace,
    /// Clear the current input line (shell Ctrl+C muscle-memory).
    ConsoleClearLine,
    /// Jump cursor to start of line (shell Ctrl+A).
    ConsoleJumpStart,
    /// Jump cursor to end of line (shell Ctrl+E).
    ConsoleJumpEnd,
    /// Kill from cursor to start of line (shell Ctrl+U).
    ConsoleKillToStart,
    /// Kill the word before cursor (shell Ctrl+W).
    ConsoleKillWord,
    /// Scroll the scrollback window up by one line (Shift+Up).
    /// Plain Up still walks command history.
    ConsoleScrollUp,
    /// Scroll the scrollback window down by one line (Shift+Down).
    ConsoleScrollDown,
    /// Scroll the scrollback window up by one page
    /// (`MAX_CONSOLE_SCROLLBACK_ROWS` lines, PgUp).
    ConsoleScrollPageUp,
    /// Scroll the scrollback window down by one page (PgDn).
    ConsoleScrollPageDown,
    /// Pin the scrollback window at the bottom (newest line trailing,
    /// Shift+End).
    ConsoleScrollEnd,
    /// Pin the scrollback window at the top (oldest reachable line,
    /// Shift+Home).
    ConsoleScrollHome,

    // ── Color Picker ─────────────────────────────────────────────
    /// Cancel the color picker (contextual mode only; ignored in standalone).
    PickerCancel,
    /// Commit the current color (contextual: close; standalone: apply to selection).
    PickerCommit,
    /// Nudge hue −15°.
    PickerNudgeHueDown,
    /// Nudge hue +15°.
    PickerNudgeHueUp,
    /// Nudge saturation −0.1.
    PickerNudgeSatDown,
    /// Nudge saturation +0.1.
    PickerNudgeSatUp,
    /// Nudge value −0.1.
    PickerNudgeValDown,
    /// Nudge value +0.1.
    PickerNudgeValUp,

    // ── Label Editor ─────────────────────────────────────────────
    /// Cancel the inline label editor (discard changes).
    LabelEditCancel,
    /// Commit the inline label editor.
    LabelEditCommit,

    // ── Text Editor ──────────────────────────────────────────────
    /// Cancel the inline text editor (discard changes).
    TextEditCancel,

    // ─────────────────────────────────────────────────────────────
    // ── Mouse-gesture Actions (Document context) ────────────────
    // The mouse handler synthesizes the gesture's canonical key
    // name (see `bind::gesture_key_name`) and feeds it through the
    // same `action_for_context` lookup as keyboard input. Every
    // gesture below can be bound to a key, and every keyboard
    // binding below can be bound to a gesture.
    // ─────────────────────────────────────────────────────────────
    /// Default-bound to `DoubleClick`. Dispatches by what the click hit:
    /// `Node` → open text editor, `PortalMarker`/`PortalText` → pan to
    /// partner endpoint, `EdgeLabel` → open inline label editor,
    /// `Empty` → fire `CreateOrphanNodeAndEdit` if it's bound (default
    /// off — the gesture is intentionally unbound for empty-canvas
    /// double-clicks).
    DoubleClickActivate,
    /// Create an unattached node at the cursor and immediately open
    /// its text editor with an empty buffer. Sibling of `CreateOrphanNode`
    /// which only creates and selects (no editor). Default unbound.
    CreateOrphanNodeAndEdit,
    /// Continuous left-button drag on empty canvas → camera pan.
    /// Default-bound to `LeftDrag` and `MiddleClick`. The dispatcher
    /// enters `DragState::Panning` on press and exits on release.
    PanCanvas,

    // ── Navigation / camera (Document context) ──────────────────
    /// Zoom the camera in by one step. Default-bound to `WheelUp`.
    ZoomIn,
    /// Zoom the camera out by one step. Default-bound to `WheelDown`.
    ZoomOut,
    /// Reset the camera zoom to 1.0.
    ZoomReset,
    /// Fit the entire mindmap tree to the viewport.
    ZoomFit,
    /// Pan the camera north (up) by one step.
    PanCameraNorth,
    /// Pan the camera south (down) by one step.
    PanCameraSouth,
    /// Pan the camera east (right) by one step.
    PanCameraEast,
    /// Pan the camera west (left) by one step.
    PanCameraWest,
    /// Center the camera on the centroid of the current selection.
    CenterOnSelection,
    /// Jump the camera + selection to the document's root node.
    JumpToRoot,

    // ── Selection (Document context) ────────────────────────────
    /// Select every node in the document.
    SelectAll,
    /// Clear the current selection.
    DeselectAll,
    /// Invert the current selection (selected ↔ unselected).
    InvertSelection,
    /// Select the parent of the currently-selected single node.
    SelectParent,
    /// Select the first child of the currently-selected single node.
    SelectChild,
    /// Select the next sibling of the currently-selected single node.
    SelectNextSibling,
    /// Select the previous sibling of the currently-selected single node.
    SelectPrevSibling,

    // ── TextEdit cursor primitives (TextEdit context) ───────────
    /// Move cursor one grapheme left.
    TextEditCursorLeft,
    /// Move cursor one grapheme right.
    TextEditCursorRight,
    /// Move cursor one visual line up.
    TextEditCursorUp,
    /// Move cursor one visual line down.
    TextEditCursorDown,
    /// Jump cursor to the start of the current line.
    TextEditCursorHome,
    /// Jump cursor to the end of the current line.
    TextEditCursorEnd,
    /// Move cursor one word left.
    TextEditWordLeft,
    /// Move cursor one word right.
    TextEditWordRight,
    /// Delete the grapheme before the cursor.
    TextEditDeleteBack,
    /// Delete the grapheme at / after the cursor.
    TextEditDeleteForward,
    /// Delete from cursor back to the start of the current word.
    TextEditDeleteWordBack,
    /// Delete from cursor forward through the current word.
    TextEditDeleteWordForward,
    /// Commit the editor's buffer to the model and close. Default unbound
    /// (Enter is literal in the multi-line node editor).
    TextEditCommit,

    // ── LabelEdit cursor primitives (LabelEdit context) ─────────
    /// Move cursor one grapheme left in the label/portal-text editor.
    LabelEditCursorLeft,
    /// Move cursor one grapheme right.
    LabelEditCursorRight,
    /// Jump cursor to the start of the buffer.
    LabelEditCursorHome,
    /// Jump cursor to the end of the buffer.
    LabelEditCursorEnd,
    /// Delete the grapheme before the cursor.
    LabelEditDeleteBack,
    /// Delete the grapheme at / after the cursor.
    LabelEditDeleteForward,

    // ── Console-verb Actions (Document context) ─────────────────
    /// Open the glyph-wheel color picker as a standalone palette.
    /// Mirrors `color picker on`.
    OpenColorPicker,
    /// Close the glyph-wheel color picker. Mirrors `color picker off`.
    CloseColorPicker,
    /// Open the inline label editor on the currently-selected edge.
    /// Mirrors `label edit`.
    LabelEditOnSelection,
    /// Toggle the FPS overlay on/off. Mirrors `fps on` ↔ `fps off`.
    ToggleFps,
    /// Toggle the FPS overlay's debug variant. Mirrors `fps debug` ↔
    /// `fps off`.
    ToggleFpsDebug,
    /// Replace the current document with a fresh blank one. Mirrors
    /// `new` (no path).
    NewDocument,

    // ── Parametric console-verb Actions (Document context) ──────
    // Each wraps a parameterised console verb so the user can bind
    // the verb directly without authoring a macro. Free-form
    // `String` payloads are parsed at dispatch time; bad values
    // emit a warn-log and the dispatch returns `Handled` (no
    // scrollback — Action arms have no scrollback surface).
    /// Mirror `anchor from=<side> to=<side>` on the selected edge.
    /// Sides: `auto|top|right|bottom|left`. Single-edge selection.
    SetEdgeAnchor {
        from: String,
        to: String,
    },
    /// Mirror `body glyph=<dot|dash|double|wave|chain>` on the
    /// selected edge.
    SetEdgeBodyGlyph(String),
    /// Mirror `border <field>=<value>` on the selected node(s).
    /// Single kv per binding (multi-kv border edits stay
    /// console-only). Field names: `preset|font|size|color|palette|
    /// field|padding|top|bottom|left|right|tl|tr|bl|br`.
    SetBorderField {
        field: String,
        value: String,
    },
    /// Mirror `cap from=<arrow|circle|diamond|none> to=<...>` on the
    /// selected edge.
    SetEdgeCap {
        from: String,
        to: String,
    },
    /// Mirror `color <axis>=<color>` on the current selection.
    /// `axis` picks the field group (background, text, or border);
    /// `value` is the user-facing color string (`#rrggbb`,
    /// `var(--name)`, palette key, etc.) which the verb-core parses.
    SetColor {
        axis: ColorAxis,
        value: String,
    },
    /// Mirror `edge type=<cross_link|parent_child>` on the selected
    /// edge.
    SetEdgeType(String),
    /// Mirror `edge display_mode=<line|portal>` on the selected edge.
    SetEdgeDisplayMode(String),
    /// Mirror `edge reset=<straight|curve|style|position>` on the
    /// selected edge.
    ResetEdge(String),
    /// Mirror `font set <family>` on the current selection. Unknown
    /// family names silently no-op (the verb path surfaces a typed
    /// error; the Action arm has no scrollback).
    SetFontFamily(String),
    /// Mirror `font <slot>=<pt>` on the current selection.
    /// `slot` picks `size|min|max`; `value` is the raw pt string
    /// parsed at dispatch time (non-finite or non-positive values
    /// silently no-op). `min` / `max` are selection-aware:
    /// applicable to edge / edge-label / portal-text channels;
    /// nodes have no screen-space clamp and no-op silently.
    SetFont {
        slot: FontSlot,
        value: String,
    },
    /// Mirror `label text=<text>` on the selected edge / portal
    /// label. Empty payload clears the label.
    SetEdgeLabelText(String),
    /// Mirror `label position=<start|middle|end>` on the selected
    /// line-mode edge. Portal selections silently no-op (they use
    /// the `position_t=<f32>` shape, not named anchors).
    SetEdgeLabelPosition(String),
    /// Mirror `spacing value=<tight|normal|wide|<float>>` on the
    /// selected edge.
    SetSpacing(String),
    /// Mirror `zoom <bound>=<zoom|unset>` on the current selection.
    /// `bound` picks `min|max`; `value` is `"unset"`, `""`, or a
    /// positive finite float string. Inverted bounds (`min > max`)
    /// silently no-op.
    SetZoom {
        bound: ZoomBound,
        value: String,
    },
    /// Mirror `zoom clear` — drop both `min_zoom_to_render` and
    /// `max_zoom_to_render` on the current selection. Unit
    /// variant — no payload.
    ClearZoom,
    /// Mirror `open <path>` — replace the current document with the
    /// one loaded from `path`. **NativeOnly** + **destructive**:
    /// touches the filesystem. Denylisted for non-User macro tiers
    /// — a hostile mindmap must not be able to load arbitrary
    /// content as the active document.
    OpenDocument(String),
    /// Mirror `save <path>` — write the current document to `path`
    /// and rebind. **NativeOnly** + **destructive**: writes to the
    /// filesystem; a hostile macro could overwrite arbitrary files.
    /// Denylisted for non-User macro tiers.
    SaveDocumentAs(String),
    /// Mirror `new <path>` — start a fresh document and bind it to
    /// `path` (writes a blank file there immediately). **NativeOnly**
    /// + **destructive**: writes to the filesystem. Denylisted for
    /// non-User macro tiers.
    NewDocumentAt(String),
}

impl Action {
    /// Whether this action mutates persistent state (filesystem,
    /// document model that bypasses the undo stack, clipboard) or
    /// reaches an editor modal that can mutate model state on
    /// commit. Consulted by `MacroSource::allows_action` so non-
    /// User macro tiers (App / Map / Inline — including hostile
    /// `.mindmap.json` content) cannot fire destructive Actions.
    /// Thin delegate to [`ActionKind::is_destructive`] — the
    /// canonical classifier lives on the discriminant enum so its
    /// match doesn't need to destructure payloads.
    pub fn is_destructive(&self) -> bool {
        ActionKind::from(self).is_destructive()
    }

    /// The input context this action belongs to. Thin delegate to
    /// [`ActionKind::context`].
    pub fn context(&self) -> InputContext {
        ActionKind::from(self).context()
    }

    /// Whether this action can fire on WASM today. Thin delegate
    /// to [`ActionKind::wasm_compatibility`] — the classification
    /// rule lives on the discriminant enum next to the
    /// `is_destructive` and `context` siblings.
    pub fn wasm_compatibility(&self) -> WasmCompatibility {
        ActionKind::from(self).wasm_compatibility()
    }
}


/// Cross-platform compatibility classification for an [`Action`].
///
/// The Mandala application targets both native (winit + desktop wgpu)
/// and WASM (browser canvas + web wgpu). Today native has every
/// modal and state machine; WASM has a curated subset (document,
/// renderer, node text editor, mouse, keyboard). The
/// [`Action::wasm_compatibility`] method classifies each variant
/// based on which target's machinery it requires.
///
/// **Where this matters.** `run_wasm.rs`'s keyboard / mouse paths
/// filter on this so a key bound to e.g. `Action::OpenConsole`
/// silently no-ops in the browser instead of triggering a panic
/// at the dispatch site. As WASM gains its own version of the
/// missing modals (see `WASM_CONVERGENCE.md`), variants migrate
/// from `NativeOnly` to `Compatible` one at a time.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum WasmCompatibility {
    /// Action works identically on native and WASM today. Its
    /// dispatch arm reads / writes only state both targets have:
    /// `MindMapDocument`, `Renderer`, `TextEditState`, mouse
    /// gestures, the macro registry. Safe to fire from a WASM
    /// `dispatch_action_for_wasm` once that path is built.
    Compatible,
    /// Action requires a native-only system not yet ported to
    /// WASM (`AppMode`, console, color picker, inline label /
    /// portal-text editors, `DragState`, filesystem `save`).
    /// Currently a no-op on WASM; the convergence path is to
    /// either port the underlying system or surface a WASM-
    /// specific equivalent and flip the classification to
    /// `Compatible`. Tracked in `WASM_CONVERGENCE.md`.
    NativeOnly,
}

mod context;
mod destructive;
mod wasm;
