// SPDX-License-Identifier: MPL-2.0

//! Pinned oracle signatures — the exact console behavior at the
//! time each row was recorded. Generated once from a run of the
//! corpus and then hand-owned: a row changes only when a change to
//! the console is *meant* to change what a user sees, and the diff
//! in the failure output is the review surface for that decision.
//!
//! Rows are positional — index N here answers input N in the
//! matching corpus in [`super::oracle_corpus`].

pub const EXEC_EXPECTED: &[&str] = &[
    "LINES commands (use `help all` to see non-applicable ones):\\n  help         List commands or print usage for one\\n  border       Configure the node border (preset, font, color, custom glyphs, palette)\\n  canvas       Edit map-wide canvas defaults (border, section frame)\\n  color        Set bg/text/border color, or pick via the glyph wheel\\n  font         Set font family / size / clamps on the selection, or list fonts\\n  fps          Toggle the FPS overlay (on | off | debug)\\n  mode         Change the active interaction mode (default / resize / node-edit)\\n  mutation     List, apply, and inspect registered mutations\\n  save         Save the current mindmap to disk\\n  open         Open a mindmap file, replacing the current one\\n  new          Start a new blank mindmap, replacing the current one\\n  node         Resize the selected node, fit it to its content, or enter node-edit mode\\n  section      Inspect, move, resize, edit text, or structurally modify a section (add / delete / split)\\n  zoom         Gate the selection's rendering on camera zoom level",
    "LINES all commands:\\n  help         List commands or print usage for one\\n  anchor       Set the from/to anchor side of the selected edge\\n  body         Set the body glyph of the selected edge\\n  border       Configure the node border (preset, font, color, custom glyphs, palette)\\n  canvas       Edit map-wide canvas defaults (border, section frame)\\n  cap          Set the start/end cap glyph of the selected edge\\n  color        Set bg/text/border color, or pick via the glyph wheel\\n  edge         Convert edge type, switch display mode, curve/straighten, or reset style/position\\n  font         Set font family / size / clamps on the selection, or list fonts\\n  fps          Toggle the FPS overlay (on | off | debug)\\n  spacing      Set the glyph spacing of the selected edge\\n  label        Edit, clear, reposition, or offset the selected edge's label\\n  mode         Change the active interaction mode (default / resize / node-edit)\\n  mutation     List, apply, and inspect registered mutations\\n  save         Save the current mindmap to disk\\n  open         Open a mindmap file, replacing the current one\\n  new          Start a new blank mindmap, replacing the current one\\n  node         Resize the selected node, fit it to its content, or enter node-edit mode\\n  section      Inspect, move, resize, edit text, or structurally modify a section (add / delete / split)\\n  zoom         Gate the selection's rendering on camera zoom level",
    "LINES color — Set bg/text/border color, or pick via the glyph wheel\\nusage: color bg\\n       color text\\n       color border\\n       color pick\\n       color picker <on|off>\\n       color <key>=<value> …\\nkeys:  bg=<#hex|var(--name)|accent|edge|fg|reset> — fill / background color\\n       text=<#hex|var(--name)|accent|edge|fg|reset> — text / label color\\n       border=<#hex|var(--name)|accent|edge|fg|reset> — frame / line color\\n       section=<idx> — target section index inside a multi-section node\\n       range=<A..B> — grapheme range A..B inside the targeted section\\ntags: color, bg, text, border, pick, picker, section, range, wheel",
    "LINES font — Set font family / size / clamps on the selection, or list fonts\\nusage: font set <family> [section=<idx>] [range=<A..B>]\\n       font list\\n       font size=<pt> [min=<pt>] [max=<pt>] [section=<idx>] [range=<A..B>]\\nkeys:  size=<pt> — target on-screen size in points\\n       min=<pt> — lower screen-space clamp in points\\n       max=<pt> — upper screen-space clamp in points\\n       section=<idx> — target section index inside a multi-section node\\n       range=<A..B> — grapheme range A..B inside the targeted section\\ntags: font, set, list, size, min, max, section, range, family, clamp, pt, smaller, larger",
    "ERR unknown command: nope",
    "ERR usage: anchor [from=<auto|top|right|bottom|left>] [to=<auto|top|right|bottom|left>]",
    "OK anchor applied",
    "LINES to already bottom",
    "ERR 'diagonal': expected auto|top|right|bottom|left",
    "ERR anchor: unknown key 'bogus'; anchor reads from | to",
    "ERR no edge selected",
    "ERR anchor: unexpected extra positional 'sideways'. Compose multiple edits via the kv form (`anchor <key>=<value> …`).",
    "ERR usage: body glyph=<dot|dash|double|wave|chain>",
    "OK body glyph set to dash",
    "ERR glyph 'nope' must be one of dot|dash|double|wave|chain",
    "ERR body: unknown key 'bogus'; body reads glyph",
    "ERR usage: border\\n  visibility: on | off | toggle | reset\\n  readout:    show\\n  staged:     preview\\n  per-field:  preset | color | padding | palette | font\\n  glyphs:     side | corner\\n  composed:   <key>=<value> …",
    "OK border on on 1 node(s)",
    "OK border: already off",
    "OK border toggled → on",
    "ERR border show: side='nope' unknown; pick top | bottom | left | right | all",
    "LINES visible: off  (toggle: `border toggle`)\\npreset:  (default)  (cycle: `border preset cycle`)\\nfont:    (default) (14 pt)  (override: `border font <family>`, source: hardcoded floor)\\ncolor:   #30b082\\npalette: (none)\\npadding: 4 px\\nsize:    373×109 px (47 cluster cols, 8 rows)\\ntop:    ───────────────────────────────────────────────\\nbottom: ───────────────────────────────────────────────\\nleft:   ││││││││\\nright:  ││││││││\\ncorners: tl=┌  tr=┐  bl=└  br=┘",
    "LINES visible: off  (toggle: `border toggle`)\\npreset:  (default)  (cycle: `border preset cycle`)\\nfont:    (default) (14 pt)  (override: `border font <family>`, source: hardcoded floor)\\ncolor (cascade):\\n  node frame (effective) = #30b082          # source: palette `coral-v3` at level 0\\n  style.frame_color    = #30b082          # the unthemed tier, set via `color border=`\\n  style.border.color   = (unset) [→ #30b082]   # set via `border color`\\npalette: (none)\\npadding: 4 px\\nsize:    373×109 px (47 cluster cols, 8 rows)\\ntop:    ───────────────────────────────────────────────\\nbottom: ───────────────────────────────────────────────\\nleft:   ││││││││\\nright:  ││││││││\\ncorners: tl=┌  tr=┐  bl=└  br=┘",
    "LINES visible: off  (toggle: `border toggle`)\\npreset:  (default)  (cycle: `border preset cycle`)\\nfont:    (default) (14 pt)  (override: `border font <family>`, source: hardcoded floor)\\ncolor:   #30b082\\npalette: (none)\\npadding: 4 px\\nsize:    373×109 px (47 cluster cols, 8 rows)\\ntop:    ───────────────────────────────────────────────",
    "OK border: no change",
    "ERR border: unknown subverb 'nope'\\n  visibility: on | off | toggle | reset\\n  readout:    show\\n  staged:     preview\\n  per-field:  preset | color | padding | palette | font\\n  glyphs:     side | corner\\n  composed:   <key>=<value> …",
    "ERR border: unknown subverb 'NOPE'\\n  visibility: on | off | toggle | reset\\n  readout:    show\\n  staged:     preview\\n  per-field:  preset | color | padding | palette | font\\n  glyphs:     side | corner\\n  composed:   <key>=<value> …",
    "OK border applied to 1 node(s)",
    "ERR preset 'nope' unknown; pick one of light | heavy | double | rounded | custom | cycle",
    "LINES border preset → 'heavy' (cycle)\\nborder applied to 1 node(s)",
    "ERR usage: border preset <light|heavy|double|rounded|custom|cycle>",
    "OK border applied to 1 node(s)",
    "ERR usage: border color <#hex|var(--name)|accent|edge|fg|reset>",
    "OK border applied to 1 node(s)",
    "ERR padding='abc' is not a number",
    "ERR usage: border padding <px>",
    "ERR border padding: unexpected extra positional '50'. Compose multiple edits via the kv form (`border <key>=<value> …`) or stage with `border preview …`.",
    "OK border applied to 1 node(s)",
    "ERR usage: border palette <name|off> [field=<frame|background|text|title>]",
    "OK border applied to 1 node(s)",
    "OK border applied to 1 node(s)",
    "ERR usage: border font <family|off> [size=<pt>]",
    "OK border applied to 1 node(s)",
    "ERR border side: 'nope' unknown; pick top | bottom | left | right | all",
    "ERR border side top: missing pattern (or 'reset' to clear)",
    "ERR usage: border side <top|bottom|left|right|all> <pattern|reset>",
    "OK border applied to 1 node(s)",
    "ERR border corner: 'nope' unknown; pick tl | tr | bl | br | all",
    "ERR border corner tl: missing glyph (or 'reset' to clear)",
    "ERR usage: border corner <tl|tr|bl|br|all> <glyph|reset>",
    "OK border applied to 1 node(s)",
    "OK border applied to 1 node(s)",
    "ERR size='abc' is not a number",
    "ERR border: unknown key 'bogus'; border reads preset | font | size | color | palette | field | padding | top | bottom | left | right | tl | tr | bl | br",
    "OK border preview active (commit / cancel to terminate)",
    "LINES border applied to 1 node(s)\\nnote: preset='heavy' auto-promoted to 'custom' (a side or corner glyph was set; non-custom presets ignore the per-node glyph override)",
    "LINES border applied to 1 node(s)\\nhint: 'custom' is the preset that lets you author per-side / per-corner glyphs. Combine it with any of: top=… bottom=… left=… right=… tl=… tr=… bl=… br=…  e.g. `border preset=custom top=\"###(*)###\" tl=\"+\" tr=\"+\" bl=\"+\" br=\"+\"`. See `format/border-patterns.md` for the side-pattern grammar.",
    "LINES border preview active (commit / cancel to terminate)\\nnote: preset='heavy' auto-promoted to 'custom' (a side or corner glyph was set; non-custom presets ignore the per-target glyph override)",
    "LINES border preview active (commit / cancel to terminate)\\nhint: 'custom' is the preset that lets you author per-side / per-corner glyphs. Combine it with any of: top=… bottom=… left=… right=… tl=… tr=… bl=… br=…  e.g. `border preview preset=custom top=\"###(*)###\" tl=\"+\" tr=\"+\" bl=\"+\" br=\"+\"`. See `format/border-patterns.md` for the side-pattern grammar.",
    "LINES canvas border updated\\nhint: 'custom' is the preset that lets you author per-side / per-corner glyphs. Combine it with any of: top=… bottom=… left=… right=… tl=… tr=… bl=… br=…  e.g. `canvas border preset=custom top=\"###(*)###\" tl=\"+\" tr=\"+\" bl=\"+\" br=\"+\"`. See `format/border-patterns.md` for the side-pattern grammar.",
    "LINES section frame applied to 1 section(s)\\nhint: 'custom' is the preset that lets you author per-side / per-corner glyphs. Combine it with any of: top=… bottom=… left=… right=… tl=… tr=… bl=… br=…  e.g. `section frame preset=custom top=\"###(*)###\" tl=\"+\" tr=\"+\" bl=\"+\" br=\"+\"`. See `format/border-patterns.md` for the side-pattern grammar.",
    "OK border preview: no active preview",
    "OK border preview: no active preview",
    "ERR border preview: unknown subverb 'nope'\\n  terminator: commit | cancel\\n  composed:   <key>=<value> …",
    "ERR border preview: unknown subverb 'NOPE'\\n  terminator: commit | cancel\\n  composed:   <key>=<value> …",
    "ERR usage: border preview\\n  terminator: commit | cancel\\n  composed:   <key>=<value> …",
    "ERR border: not applicable to edges",
    "ERR border: unexpected positional 'preset' alongside a kv pair — did you mean to quote a multi-word value? e.g. `border color=\"#fff preset\"`",
    "OK border preview active (commit / cancel to terminate)",
    "ERR border show: unknown key 'color'; border show reads side. `color=` belongs to the composed form: `border color=<value>`",
    "ERR border on: unknown key 'color'; border on takes no keys. `color=` belongs to the composed form: `border color=<value>`",
    "ERR border: unknown subverb 'nope'\\n  visibility: on | off | toggle | reset\\n  readout:    show\\n  staged:     preview\\n  per-field:  preset | color | padding | palette | font\\n  glyphs:     side | corner\\n  composed:   <key>=<value> …",
    "ERR border preview: unknown subverb 'nope'\\n  terminator: commit | cancel\\n  composed:   <key>=<value> …",
    "ERR canvas border preview: unknown subverb 'nope'\\n  terminator: commit | cancel\\n  composed:   <key>=<value> …",
    "ERR border preview: unexpected positional 'Palette' alongside a kv pair — did you mean to quote a multi-word value? e.g. `border preview palette=\"My Palette\"`",
    "ERR border: unexpected positional 'Sans' alongside a kv pair — did you mean to quote a multi-word value? e.g. `border font=\"DejaVu Sans\"`",
    "ERR usage: canvas\\n  subject: border | section-frame",
    "ERR canvas: unknown subverb 'nope'\\n  subject: border | section-frame",
    "ERR canvas: unknown subverb 'NOPE'\\n  subject: border | section-frame",
    "ERR usage: canvas border\\n  readout:   show\\n  override:  reset\\n  staged:    preview\\n  per-field: preset | color | padding | palette | font\\n  glyphs:    side | corner\\n  composed:  <key>=<value> …",
    "LINES canvas border: (no map-wide default — every framed node falls back to its per-node `style.frame_color` / hardcoded glyph defaults)",
    "OK canvas border: no change",
    "OK canvas border updated",
    "ERR preset 'nope' unknown; pick one of light | heavy | double | rounded | custom | cycle",
    "ERR canvas border: unknown subverb 'nope'\\n  readout:   show\\n  override:  reset\\n  staged:    preview\\n  per-field: preset | color | padding | palette | font\\n  glyphs:    side | corner\\n  composed:  <key>=<value> …",
    "ERR canvas border: unknown subverb 'NOPE'\\n  readout:   show\\n  override:  reset\\n  staged:    preview\\n  per-field: preset | color | padding | palette | font\\n  glyphs:    side | corner\\n  composed:  <key>=<value> …",
    "ERR canvas border: unknown key 'bogus'; canvas border reads preset | font | size | color | palette | field | padding | top | bottom | left | right | tl | tr | bl | br",
    "OK canvas border updated",
    "ERR padding='abc' is not a number",
    "ERR canvas border padding: unexpected extra positional '50'. Compose multiple edits via the kv form (`canvas border <key>=<value> …`) or stage with `canvas border preview …`.",
    "OK canvas border updated",
    "OK canvas border updated",
    "ERR canvas border corner: 'nope' unknown; pick tl | tr | bl | br | all",
    "ERR canvas border: unexpected positional 'preset' alongside a kv pair — did you mean to quote a multi-word value? e.g. `canvas border color=\"#fff preset\"`",
    "ERR canvas border show: unknown key 'color'; canvas border show takes no keys. `color=` belongs to the composed form: `canvas border color=<value>`",
    "ERR canvas border reset: unknown key 'color'; canvas border reset takes no keys. `color=` belongs to the composed form: `canvas border color=<value>`",
    "ERR canvas border preview commit: unknown key 'color'; canvas border preview commit takes no keys. `color=` belongs to the composed form: `canvas border preview color=<value>`",
    "ERR canvas section-frame focused: unexpected positional 'preset' alongside a kv pair — did you mean to quote a multi-word value? e.g. `canvas section-frame focused color=\"#fff focused preset\"`",
    "ERR canvas section-frame focused show: unknown key 'color'; canvas section-frame focused show takes no keys. `color=` belongs to the composed form: `canvas section-frame focused color=<value>`",
    "ERR usage: canvas section-frame\\n  modifier:  focused\\n  readout:   show\\n  override:  reset\\n  staged:    preview\\n  per-field: preset | color | padding | palette | font\\n  glyphs:    side | corner\\n  composed:  <key>=<value> …",
    "LINES canvas section-frame: (no map-wide default — falls back to hardcoded light floor)",
    "OK canvas section-frame: no change",
    "ERR canvas section-frame: unknown subverb 'nope'\\n  modifier:  focused\\n  readout:   show\\n  override:  reset\\n  staged:    preview\\n  per-field: preset | color | padding | palette | font\\n  glyphs:    side | corner\\n  composed:  <key>=<value> …",
    "ERR canvas section-frame: unknown subverb 'NOPE'\\n  modifier:  focused\\n  readout:   show\\n  override:  reset\\n  staged:    preview\\n  per-field: preset | color | padding | palette | font\\n  glyphs:    side | corner\\n  composed:  <key>=<value> …",
    "LINES canvas section-frame focused: (no map-wide default — falls back to hardcoded heavy floor)",
    "OK canvas section-frame focused: no change",
    "ERR canvas section-frame focused: unknown subverb 'nope'\\n  readout:   show\\n  override:  reset\\n  staged:    preview\\n  per-field: preset | color | padding | palette | font\\n  glyphs:    side | corner\\n  composed:  <key>=<value> …",
    "ERR canvas section-frame focused: unknown subverb 'NOPE'\\n  readout:   show\\n  override:  reset\\n  staged:    preview\\n  per-field: preset | color | padding | palette | font\\n  glyphs:    side | corner\\n  composed:  <key>=<value> …",
    "OK canvas section-frame updated",
    "OK canvas section-frame focused updated",
    "OK canvas border preview: no active preview",
    "OK canvas border preview: no active preview",
    "ERR canvas border preview: unknown subverb 'nope'\\n  terminator: commit | cancel\\n  composed:   <key>=<value> …",
    "ERR canvas border preview: unknown subverb 'NOPE'\\n  terminator: commit | cancel\\n  composed:   <key>=<value> …",
    "ERR canvas section-frame preview: unknown subverb 'NOPE'\\n  terminator: commit | cancel\\n  composed:   <key>=<value> …",
    "ERR canvas section-frame focused preview: unknown subverb 'NOPE'\\n  terminator: commit | cancel\\n  composed:   <key>=<value> …",
    "ERR usage: cap [from=<arrow|circle|diamond|none>] [to=<arrow|circle|diamond|none>]",
    "OK cap applied",
    "LINES cap to already none",
    "ERR 'nope': expected arrow|circle|diamond|none",
    "ERR cap: unknown key 'bogus'; cap reads from | to",
    "ERR usage: color\\n  picker:   bg | text | border | pick | picker\\n  composed: <key>=<value> …",
    "OK color applied",
    "ERR bg: unknown color 'nope'",
    "ERR color: unknown key 'bogus'; color reads bg | text | border | section | range",
    "OK ",
    "OK ",
    "OK ",
    "OK ",
    "OK ",
    "OK ",
    "ERR usage: color picker <on|off>",
    "ERR usage: color picker <on|off>",
    "ERR color: unknown subverb 'nope'\\n  picker:   bg | text | border | pick | picker\\n  composed: <key>=<value> …",
    "ERR color bg: not applicable to a section (section-level chrome doesn't exist)",
    "ERR bg: not applicable to a section (section-level chrome doesn't exist)",
    "ERR color: section='abc' is not a non-negative integer",
    "OK color applied to section 0 range 0..2",
    "ERR color: range=A..B requires section=N — ranges target grapheme indices inside one section",
    "ERR color: range='zz' — expected `start..end` (e.g. `range=2..7`)",
    "ERR usage: edge [type=<cross_link|parent_child>] [display_mode=<line|portal>] [reset=<straight|curve|style|position>]",
    "OK edge applied",
    "ERR type 'nope' must be cross_link or parent_child",
    "ERR connection already straight",
    "ERR reset 'nope' must be straight, curve, style, or position",
    "OK edge applied",
    "ERR display_mode 'nope' must be line or portal",
    "ERR edge: unknown key 'bogus'; edge reads type | display_mode | reset",
    "ERR usage: font\\n  family:   set | list\\n  composed: <key>=<value> …",
    "ERR usage: font set <family> [section=<idx>] [range=<A..B>]",
    "ERR font: 'NoSuchFamilyHere' is not a loaded font; try `font list`",
    "ERR font: unknown subverb 'nope'\\n  family:   set | list\\n  composed: <key>=<value> …",
    "OK font applied",
    "ERR size='abc' is not a number",
    "ERR size='0' must be positive and finite; got 0",
    "ERR font: unknown key 'bogus'; font reads size | min | max | section | range",
    "ERR font: min=8 > max=4 (inverted bounds)",
    "ERR font: range=A..B requires section=N — ranges target grapheme indices inside one section",
    "OK font applied to section 0 range 0..2",
    "ERR font: range='zz' — expected `start..end` (e.g. `range=2..7`)",
    "ERR font: section='abc' is not a non-negative integer",
    "ERR min/max: sections have no screen-space clamps",
    "ERR usage: fps\\n  overlay: on | off | debug",
    "OK ",
    "OK ",
    "OK ",
    "ERR fps: unknown subverb 'nope'\\n  overlay: on | off | debug",
    "ERR usage: spacing value=<float|tight|normal|wide>",
    "OK spacing set to tight",
    "OK spacing set to 3.5",
    "ERR 'nope' must be a preset (tight|normal|wide) or a float",
    "ERR spacing: unknown key 'bogus'; spacing reads value",
    "ERR usage: label\\n  editor:   edit\\n  reset:    clear\\n  composed: <key>=<value> …",
    "ERR no edge selected",
    "OK label applied",
    "OK label applied",
    "ERR position 'nope' must be start|middle|end",
    "ERR position_t already ≈ 0.5000",
    "ERR position_t 'abc' is not a number",
    "OK label applied",
    "ERR label: unknown key 'bogus'; label reads text | position | position_t | perpendicular",
    "ERR label: unknown subverb 'nope'\\n  editor:   edit\\n  reset:    clear\\n  composed: <key>=<value> …",
    "ERR usage: mode\\n  modes: default | resize | node-edit",
    "OK mode: returning to Default",
    "OK entering resize mode",
    "OK entering node-edit mode on '0'",
    "ERR mode: unknown subverb 'nope'\\n  modes: default | resize | node-edit",
    "ERR usage: mutation\\n  registry: list | apply | help | inspect",
    "OK no mutations registered",
    "OK no mutations registered",
    "ERR mutation apply needs an id (`mutation apply <id>`)",
    "ERR unknown mutation: no-such-mutation",
    "ERR mutation help needs an id",
    "ERR unknown mutation: no-such-mutation",
    "ERR mutation inspect needs an id",
    "ERR unknown mutation: no-such-mutation",
    "ERR mutation: unknown subverb 'nope'\\n  registry: list | apply | help | inspect",
    "ERR mutation list: unknown key 'x'; mutation list takes no keys",
    "ERR usage: node\\n  geometry: resize | fit\\n  editor:   edit",
    "OK node '0' fitted to content",
    "OK entering node-edit mode on '0'",
    "ERR node resize: <w> must be a number",
    "OK node '0' resized to 120×60",
    "ERR node resize: <w> must be a number",
    "ERR node: unknown subverb 'nope'\\n  geometry: resize | fit\\n  editor:   edit",
    "ERR usage: open <path>",
    "ERR open: unexpected extra positional 'b.mindmap.json'.",
    "ERR no file path bound; use `save <path>` to choose one",
    "OK new map (no file path; use `save <path>` to bind one)",
    "ERR usage: section\\n  geometry:  move | resize\\n  readout:   show\\n  text:      text\\n  editor:    edit\\n  structure: add | delete | split\\n  subject:   frame",
    "ERR section: node '0' has 2 sections — pick one (click) or pass section=<idx>",
    "ERR section: unknown subverb 'nope'\\n  geometry:  move | resize\\n  readout:   show\\n  text:      text\\n  editor:    edit\\n  structure: add | delete | split\\n  subject:   frame",
    "ERR section: node '0' has 2 sections — pick one (click) or pass section=<idx>",
    "ERR section[0] extends past node right edge (201 > 200)",
    "ERR section move: cannot mix delta form (dx/dy) and absolute form (x/y) — pick one",
    "ERR section[0] extends past node right edge (201 > 200)",
    "ERR section move: dx='abc' is not a number",
    "ERR section move: unknown key 'bogus'; section move reads dx | dy | x | y | section",
    "OK section: no change",
    "OK section[0] resized",
    "ERR usage: section resize w=<f64> h=<f64> [section=<idx>] | section resize fill [section=<idx>]",
    "ERR section resize: unknown key 'bogus'; section resize reads w | h | section",
    "ERR section resize: unknown key 'w'; section resize reads section. `w=` belongs to another form: `section resize w=<f64> h=<f64> [section=<idx>]`",
    "OK section[0] text replaced (runs preserved)",
    "OK section[0] text replaced (runs cleared)",
    "ERR section text: runs='nope' not recognized; use 'preserve' or 'clear'",
    "ERR section text: unknown key 'bogus'; section text reads text | runs | section",
    "OK section[2] added on node '0'",
    "OK section[0] added on node '0'",
    "ERR section add: at='abc' is not a non-negative integer",
    "ERR section add: unknown key 'bogus'; section add reads at | text",
    "OK section[0] deleted from node '0'",
    "ERR section delete: unknown key 'bogus'; section delete reads section",
    "ERR section split: at=<grapheme> required — pass an integer grapheme index (use `section show` to see the current section's grapheme count); split-at-end-of-text (the prior default) silently created an empty suffix section",
    "OK section[0] split — new section at index 1",
    "ERR section split: at='abc' is not a non-negative integer",
    "ERR section split: unknown key 'bogus'; section split reads at | section",
    "ERR section show: unknown key 'bogus'; section show reads section",
    "ERR section[99] not found on node '0'",
    "ERR section: section='abc' is not a non-negative integer",
    "OK opening editor on section[0]…",
    "ERR section edit: unknown key 'bogus'; section edit reads section",
    "ERR usage: section frame\\n  readout:  show\\n  override: reset\\n  staged:   preview\\n  composed: <key>=<value> …",
    "LINES section frame: node='0' section=0\\n  [unfocused]\\n    source:    hardcoded light floor\\n    preset:    light\\n    font:      (default)\\n    size:      10 pt\\n    color:     #00E5FF\\n    palette:   (none)\\n    glyphs:    (preset 'light' defaults)\\n  [focused]\\n    source:    hardcoded heavy floor\\n    preset:    heavy\\n    font:      (default)\\n    size:      10 pt\\n    color:     #00E5FF\\n    palette:   (none)\\n    glyphs:    (preset 'heavy' defaults)",
    "OK section frame: no change",
    "ERR section frame: unknown subverb 'nope'\\n  readout:  show\\n  override: reset\\n  staged:   preview\\n  composed: <key>=<value> …",
    "ERR section frame: unknown subverb 'NOPE'\\n  readout:  show\\n  override: reset\\n  staged:   preview\\n  composed: <key>=<value> …",
    "ERR section frame: unknown subverb 'nope'\\n  readout:  show\\n  override: reset\\n  staged:   preview\\n  composed: <key>=<value> …",
    "ERR section frame: unexpected positional 'Palette' alongside a kv pair — did you mean to quote a multi-word value? e.g. `section frame palette=\"My Palette\"`",
    "OK section frame applied to 1 section(s)",
    "ERR section frame: unknown key 'bogus'; section frame reads preset | font | size | color | palette | field | padding | top | bottom | left | right | tl | tr | bl | br | section",
    "OK section frame preview active (commit / cancel to terminate)",
    "OK section frame preview: no active preview",
    "OK section frame preview: no active preview",
    "ERR section frame preview: unknown subverb 'nope'\\n  terminator: commit | cancel\\n  composed:   <key>=<value> …",
    "ERR section frame preview: unknown subverb 'NOPE'\\n  terminator: commit | cancel\\n  composed:   <key>=<value> …",
    "OK section frame applied to 1 section(s)",
    "ERR section frame: section='abc' is not a non-negative integer",
    "LINES section[0] of node \"0\"\\n  text:     \"Lord God\"\\n  runs:     1 runs (flags: 1 bold, 0 italic, 1 underline, 0 hyperlink)\\n  offset:   (0.0, 0.0)\\n  size:     None [fill parent: 373.5 × 109.0]\\n  channel:  None [→ index 0]\\n  bindings: 0 triggers\\n  frame:    (falls back to canvas default / floor)",
    "ERR section: requires a node or section selection",
    "ERR section: requires a node or section selection",
    "OK border on on 2 node(s)",
    "LINES font: applied to 2 node(s)",
    "LINES min/max: nodes have no screen-space clamps",
    "OK color applied",
    "ERR usage: zoom\\n  reset:  clear\\n  bounds: <key>=<value> …",
    "OK zoom: no change on node",
    "OK zoom applied to node",
    "OK zoom: no change on node",
    "ERR min='abc' is not a number or `unset`",
    "ERR min='0' must be positive and finite or `unset`; got 0",
    "ERR zoom: min=2 > max=1 (inverted bounds)",
    "ERR zoom: unknown key 'bogus'; zoom reads min | max",
    "ERR zoom: unknown subverb 'nope'\\n  reset:  clear\\n  bounds: <key>=<value> …",
    "ERR zoom: no selection",
    "LINES all commands:\\n  help         List commands or print usage for one\\n  anchor       Set the from/to anchor side of the selected edge\\n  body         Set the body glyph of the selected edge\\n  border       Configure the node border (preset, font, color, custom glyphs, palette)\\n  canvas       Edit map-wide canvas defaults (border, section frame)\\n  cap          Set the start/end cap glyph of the selected edge\\n  color        Set bg/text/border color, or pick via the glyph wheel\\n  edge         Convert edge type, switch display mode, curve/straighten, or reset style/position\\n  font         Set font family / size / clamps on the selection, or list fonts\\n  fps          Toggle the FPS overlay (on | off | debug)\\n  spacing      Set the glyph spacing of the selected edge\\n  label        Edit, clear, reposition, or offset the selected edge's label\\n  mode         Change the active interaction mode (default / resize / node-edit)\\n  mutation     List, apply, and inspect registered mutations\\n  save         Save the current mindmap to disk\\n  open         Open a mindmap file, replacing the current one\\n  new          Start a new blank mindmap, replacing the current one\\n  node         Resize the selected node, fit it to its content, or enter node-edit mode\\n  section      Inspect, move, resize, edit text, or structurally modify a section (add / delete / split)\\n  zoom         Gate the selection's rendering on camera zoom level",
    "LINES border — Configure the node border (preset, font, color, custom glyphs, palette)\\nusage: border on\\n       border off\\n       border toggle\\n       border show [verbose] [side=<top|bottom|left|right|all>]\\n       border reset\\n       border preview commit\\n       border preview cancel\\n       border preview <key>=<value> …\\n       border preset <light|heavy|double|rounded|custom|cycle>\\n       border color <#hex|var(--name)|accent|edge|fg|reset>\\n       border padding <px>\\n       border palette <name|off> [field=<frame|background|text|title>]\\n       border font <family|off> [size=<pt>]\\n       border side <top|bottom|left|right|all> <pattern|reset>\\n       border corner <tl|tr|bl|br|all> <glyph|reset>\\n       border <key>=<value> …\\nkeys:  preset=<light|heavy|double|rounded|custom> — light | heavy | double | rounded | custom\\n       font=<family|off> — font family for border glyphs (use `font list` for names)\\n       size=<pt> — border glyph size in points\\n       color=<#hex|var(--name)|accent|edge|fg|reset> — #hex, var(--name), accent | edge | fg, or 'reset'\\n       palette=<name|off> — palette name to cycle per-glyph colors, or 'off'\\n       field=<frame|background|text|title> — frame | background | text | title\\n       padding=<px> — border-to-content padding in pixels\\n       top=<pattern> — side pattern: `prefix(fill)suffix` or atomic\\n       bottom=<pattern> — side pattern: `prefix(fill)suffix` or atomic\\n       left=<pattern> — side pattern: `prefix(fill)suffix` or atomic\\n       right=<pattern> — side pattern: `prefix(fill)suffix` or atomic\\n       tl=<glyph> — single corner glyph (escapes apply)\\n       tr=<glyph> — single corner glyph (escapes apply)\\n       bl=<glyph> — single corner glyph (escapes apply)\\n       br=<glyph> — single corner glyph (escapes apply)\\n       side=<top|bottom|left|right|all> — filter readout to one side (top|bottom|left|right|all)\\ntags: border, on, off, toggle, show, reset, preview, commit, cancel, preset, font, size, color, palette, field, padding, top, bottom, left, right, tl, tr, bl, br, side, corner, frame, glyph, pattern, rounded, heavy, double, light, custom",
    "OK border applied to 1 node(s)",
    "OK border preview: no active preview",
    "OK canvas border updated",
    "LINES canvas section-frame focused: (no map-wide default — falls back to hardcoded heavy floor)",
    "OK ",
    "ERR font: 'NoSuchFamilyHere' is not a loaded font; try `font list`",
    "OK ",
    "ERR no edge selected",
    "OK mode: returning to Default",
    "OK no mutations registered",
    "OK node '0' fitted to content",
    "ERR section frame: node '0' has 2 sections — pick one (click) or pass section=<idx>",
    "OK section frame preview: no active preview",
    "OK zoom: no change on node",
    "ERR border: unknown key 'TOP'; border reads preset | font | size | color | palette | field | padding | top | bottom | left | right | tl | tr | bl | br",
    "ERR font: unknown key 'SIZE'; font reads size | min | max | section | range",
];

/// A prefix, not a whole signature — see
/// [`super::oracle_corpus::EXEC_PREFIX_CORPUS`] for which tail is
/// cut off, why it is the only one, and what the three rows that
/// used to keep it company cost while they were here.
pub const EXEC_PREFIX_EXPECTED: &[&str] = &[
    "ERR open /nonexistent-dir-xyz/x.mindmap.json: Failed to read file /nonexistent-dir-xyz/x.mindmap.json:",
];

pub const COMPLETION_EXPECTED: &[&str] = &[
    "help [List commands or print usage for one] ; border [Configure the node border (preset, font, color, custom glyphs, palette)] ; canvas [Edit map-wide canvas defaults (border, section frame)] ; color [Set bg/text/border color, or pick via the glyph wheel] ; font [Set font family / size / clamps on the selection, or list fonts] ; fps [Toggle the FPS overlay (on | off | debug)] ; mode [Change the active interaction mode (default / resize / node-edit)] ; mutation [List, apply, and inspect registered mutations] ; save [Save the current mindmap to disk] ; open [Open a mindmap file, replacing the current one] ; new [Start a new blank mindmap, replacing the current one] ; node [Resize the selected node, fit it to its content, or enter node-edit mode] ; section [Inspect, move, resize, edit text, or structurally modify a section (add / delete / split)] ; zoom [Gate the selection's rendering on camera zoom level]",
    "color [Set bg/text/border color, or pick via the glyph wheel]",
    "body [Set the body glyph of the selected edge]",
    "help [List commands or print usage for one] ; anchor [Set the from/to anchor side of the selected edge] ; body [Set the body glyph of the selected edge] ; border [Configure the node border (preset, font, color, custom glyphs, palette)] ; canvas [Edit map-wide canvas defaults (border, section frame)] ; cap [Set the start/end cap glyph of the selected edge] ; color [Set bg/text/border color, or pick via the glyph wheel] ; edge [Convert edge type, switch display mode, curve/straighten, or reset style/position] ; font [Set font family / size / clamps on the selection, or list fonts] ; fps [Toggle the FPS overlay (on | off | debug)] ; spacing [Set the glyph spacing of the selected edge] ; label [Edit, clear, reposition, or offset the selected edge's label] ; mode [Change the active interaction mode (default / resize / node-edit)] ; mutation [List, apply, and inspect registered mutations] ; save [Save the current mindmap to disk] ; open [Open a mindmap file, replacing the current one] ; new [Start a new blank mindmap, replacing the current one] ; node [Resize the selected node, fit it to its content, or enter node-edit mode] ; section [Inspect, move, resize, edit text, or structurally modify a section (add / delete / split)] ; zoom [Gate the selection's rendering on camera zoom level] ; all [include commands the current selection can't use]",
    "color [Set bg/text/border color, or pick via the glyph wheel]",
    "anchor [Set the from/to anchor side of the selected edge] ; all [include commands the current selection can't use]",
    "from= [which side of the source node the edge leaves] ; to= [which side of the target node the edge arrives at]",
    "from= [which side of the source node the edge leaves]",
    "auto ; top ; right ; bottom ; left",
    "top",
    "glyph= [the repeated glyph the edge body is drawn from]",
    "dot ; dash ; double ; wave ; chain",
    "dot ; dash ; double",
    "on [show the border] ; off [hide the border] ; toggle [flip show_frame per node] ; show [print the resolved config (use [side=…] [verbose])] ; reset [drop the per-node override] ; preview [stage a preview without writing the model (commit/cancel terminates)] ; preset [pick light|heavy|double|rounded|custom or `cycle`] ; color [set border color (#hex|var|accent|edge|fg|reset)] ; padding [set border padding in pixels] ; palette [cycle a palette across glyphs (or `off`)] ; font [set border glyph font family (with optional size=)] ; side [set per-side glyph (top|bottom|left|right|all)] ; corner [set per-corner glyph (tl|tr|bl|br|all)] ; preset= [light | heavy | double | rounded | custom] ; font= [font family for border glyphs (use `font list` for names)] ; size= [border glyph size in points] ; color= [#hex, var(--name), accent | edge | fg, or 'reset'] ; palette= [palette name to cycle per-glyph colors, or 'off'] ; field= [frame | background | text | title] ; padding= [border-to-content padding in pixels] ; top= [side pattern: `prefix(fill)suffix` or atomic] ; bottom= [side pattern: `prefix(fill)suffix` or atomic] ; left= [side pattern: `prefix(fill)suffix` or atomic] ; right= [side pattern: `prefix(fill)suffix` or atomic] ; tl= [single corner glyph (escapes apply)] ; tr= [single corner glyph (escapes apply)] ; bl= [single corner glyph (escapes apply)] ; br= [single corner glyph (escapes apply)]",
    "preview [stage a preview without writing the model (commit/cancel terminates)] ; preset [pick light|heavy|double|rounded|custom or `cycle`] ; preset= [light | heavy | double | rounded | custom]",
    "light [thin lines (default)] ; heavy [bold lines] ; double [double lines] ; rounded [thin lines with rounded corners] ; custom [user-supplied per-side / per-corner glyphs] ; cycle [advance to the next preset (wraps)]",
    "heavy [bold lines]",
    "accent ; edge ; fg ; reset",
    "My Palette ; autumn ; coral ; coral-v3 ; mountain ; navy-v3 ; rainbow ; rocky ; sandy ; stars-v3 ; summer ; sweet ; off [clear palette cycling]",
    "top ; bottom ; left ; right ; all",
    "reset [restore the slot's preset's default glyph]",
    "tl ; tr ; bl ; br ; all",
    "reset [restore the slot's preset's default glyph]",
    "verbose [surface the dual color cascade (frame_color vs border.color)] ; side= [filter readout to one side (top|bottom|left|right|all)]",
    "top ; bottom ; left ; right ; all",
    "commit [write the staged preview through and clear the slot] ; cancel [discard the staged preview, no model write] ; preset= [light | heavy | double | rounded | custom] ; font= [font family for border glyphs (use `font list` for names)] ; size= [border glyph size in points] ; color= [#hex, var(--name), accent | edge | fg, or 'reset'] ; palette= [palette name to cycle per-glyph colors, or 'off'] ; field= [frame | background | text | title] ; padding= [border-to-content padding in pixels] ; top= [side pattern: `prefix(fill)suffix` or atomic] ; bottom= [side pattern: `prefix(fill)suffix` or atomic] ; left= [side pattern: `prefix(fill)suffix` or atomic] ; right= [side pattern: `prefix(fill)suffix` or atomic] ; tl= [single corner glyph (escapes apply)] ; tr= [single corner glyph (escapes apply)] ; bl= [single corner glyph (escapes apply)] ; br= [single corner glyph (escapes apply)]",
    "-",
    "on [show the border] ; off [hide the border] ; toggle [flip show_frame per node] ; show [print the resolved config (use [side=…] [verbose])] ; reset [drop the per-node override] ; preview [stage a preview without writing the model (commit/cancel terminates)] ; preset= [light | heavy | double | rounded | custom] ; font= [font family for border glyphs (use `font list` for names)] ; size= [border glyph size in points] ; color= [#hex, var(--name), accent | edge | fg, or 'reset'] ; palette= [palette name to cycle per-glyph colors, or 'off'] ; field= [frame | background | text | title] ; padding= [border-to-content padding in pixels] ; top= [side pattern: `prefix(fill)suffix` or atomic] ; bottom= [side pattern: `prefix(fill)suffix` or atomic] ; left= [side pattern: `prefix(fill)suffix` or atomic] ; right= [side pattern: `prefix(fill)suffix` or atomic] ; tl= [single corner glyph (escapes apply)] ; tr= [single corner glyph (escapes apply)] ; bl= [single corner glyph (escapes apply)] ; br= [single corner glyph (escapes apply)]",
    "light [thin lines (default)] ; heavy [bold lines] ; double [double lines] ; rounded [thin lines with rounded corners] ; custom [user-supplied per-side / per-corner glyphs] ; cycle [advance to the next preset (wraps)]",
    "light [thin lines (default)] ; heavy [bold lines] ; double [double lines] ; rounded [thin lines with rounded corners] ; custom [user-supplied per-side / per-corner glyphs]",
    "frame ; background ; text ; title",
    "-",
    "-",
    "-",
    "border [the map-wide default node border] ; section-frame [the map-wide default section-frame border]",
    "border [the map-wide default node border]",
    "show [print the resolved canvas default] ; reset [drop the canvas-level default] ; preview [stage a preview without writing the model (commit/cancel terminates)] ; preset [pick light|heavy|double|rounded|custom or `cycle`] ; color [set border color (#hex|var|accent|edge|fg|reset)] ; padding [set border padding in pixels] ; palette [cycle a palette across glyphs (or `off`)] ; font [set border glyph font family (with optional size=)] ; side [set per-side glyph (top|bottom|left|right|all)] ; corner [set per-corner glyph (tl|tr|bl|br|all)] ; preset= [light | heavy | double | rounded | custom] ; font= [font family for border glyphs (use `font list` for names)] ; size= [border glyph size in points] ; color= [#hex, var(--name), accent | edge | fg, or 'reset'] ; palette= [palette name to cycle per-glyph colors, or 'off'] ; field= [frame | background | text | title] ; padding= [border-to-content padding in pixels] ; top= [side pattern: `prefix(fill)suffix` or atomic] ; bottom= [side pattern: `prefix(fill)suffix` or atomic] ; left= [side pattern: `prefix(fill)suffix` or atomic] ; right= [side pattern: `prefix(fill)suffix` or atomic] ; tl= [single corner glyph (escapes apply)] ; tr= [single corner glyph (escapes apply)] ; bl= [single corner glyph (escapes apply)] ; br= [single corner glyph (escapes apply)]",
    "preview [stage a preview without writing the model (commit/cancel terminates)] ; preset [pick light|heavy|double|rounded|custom or `cycle`] ; preset= [light | heavy | double | rounded | custom]",
    "light [thin lines (default)] ; heavy [bold lines] ; double [double lines] ; rounded [thin lines with rounded corners] ; custom [user-supplied per-side / per-corner glyphs] ; cycle [advance to the next preset (wraps)]",
    "commit [write the staged preview through and clear the slot] ; cancel [discard the staged preview, no model write] ; preset= [light | heavy | double | rounded | custom] ; font= [font family for border glyphs (use `font list` for names)] ; size= [border glyph size in points] ; color= [#hex, var(--name), accent | edge | fg, or 'reset'] ; palette= [palette name to cycle per-glyph colors, or 'off'] ; field= [frame | background | text | title] ; padding= [border-to-content padding in pixels] ; top= [side pattern: `prefix(fill)suffix` or atomic] ; bottom= [side pattern: `prefix(fill)suffix` or atomic] ; left= [side pattern: `prefix(fill)suffix` or atomic] ; right= [side pattern: `prefix(fill)suffix` or atomic] ; tl= [single corner glyph (escapes apply)] ; tr= [single corner glyph (escapes apply)] ; bl= [single corner glyph (escapes apply)] ; br= [single corner glyph (escapes apply)]",
    "light [thin lines (default)] ; heavy [bold lines] ; double [double lines] ; rounded [thin lines with rounded corners] ; custom [user-supplied per-side / per-corner glyphs]",
    "-",
    "accent ; edge ; fg ; reset",
    "My Palette ; autumn ; coral ; coral-v3 ; mountain ; navy-v3 ; rainbow ; rocky ; sandy ; stars-v3 ; summer ; sweet ; off [clear palette cycling]",
    "-",
    "top ; bottom ; left ; right ; all",
    "reset [restore the slot's preset's default glyph]",
    "tl ; tr ; bl ; br ; all",
    "reset [restore the slot's preset's default glyph]",
    "-",
    "reset [restore the slot's preset's default glyph]",
    "show [print the resolved canvas default] ; reset [drop the canvas-level default] ; preview [stage a preview without writing the model (commit/cancel terminates)] ; preset= [light | heavy | double | rounded | custom] ; font= [font family for border glyphs (use `font list` for names)] ; size= [border glyph size in points] ; color= [#hex, var(--name), accent | edge | fg, or 'reset'] ; palette= [palette name to cycle per-glyph colors, or 'off'] ; field= [frame | background | text | title] ; padding= [border-to-content padding in pixels] ; top= [side pattern: `prefix(fill)suffix` or atomic] ; bottom= [side pattern: `prefix(fill)suffix` or atomic] ; left= [side pattern: `prefix(fill)suffix` or atomic] ; right= [side pattern: `prefix(fill)suffix` or atomic] ; tl= [single corner glyph (escapes apply)] ; tr= [single corner glyph (escapes apply)] ; bl= [single corner glyph (escapes apply)] ; br= [single corner glyph (escapes apply)]",
    "focused [target the focused section's frame rather than the unfocused default] ; show [print the resolved canvas default] ; reset [drop the canvas-level default] ; preview [stage a preview without writing the model (commit/cancel terminates)] ; preset= [light | heavy | double | rounded | custom] ; font= [font family for border glyphs (use `font list` for names)] ; size= [border glyph size in points] ; color= [#hex, var(--name), accent | edge | fg, or 'reset'] ; palette= [palette name to cycle per-glyph colors, or 'off'] ; field= [frame | background | text | title] ; padding= [border-to-content padding in pixels] ; top= [side pattern: `prefix(fill)suffix` or atomic] ; bottom= [side pattern: `prefix(fill)suffix` or atomic] ; left= [side pattern: `prefix(fill)suffix` or atomic] ; right= [side pattern: `prefix(fill)suffix` or atomic] ; tl= [single corner glyph (escapes apply)] ; tr= [single corner glyph (escapes apply)] ; bl= [single corner glyph (escapes apply)] ; br= [single corner glyph (escapes apply)]",
    "show [print the resolved canvas default] ; reset [drop the canvas-level default] ; preview [stage a preview without writing the model (commit/cancel terminates)] ; preset= [light | heavy | double | rounded | custom] ; font= [font family for border glyphs (use `font list` for names)] ; size= [border glyph size in points] ; color= [#hex, var(--name), accent | edge | fg, or 'reset'] ; palette= [palette name to cycle per-glyph colors, or 'off'] ; field= [frame | background | text | title] ; padding= [border-to-content padding in pixels] ; top= [side pattern: `prefix(fill)suffix` or atomic] ; bottom= [side pattern: `prefix(fill)suffix` or atomic] ; left= [side pattern: `prefix(fill)suffix` or atomic] ; right= [side pattern: `prefix(fill)suffix` or atomic] ; tl= [single corner glyph (escapes apply)] ; tr= [single corner glyph (escapes apply)] ; bl= [single corner glyph (escapes apply)] ; br= [single corner glyph (escapes apply)]",
    "focused [target the focused section's frame rather than the unfocused default] ; show [print the resolved canvas default] ; reset [drop the canvas-level default] ; preview [stage a preview without writing the model (commit/cancel terminates)] ; preset [pick light|heavy|double|rounded|custom or `cycle`] ; color [set border color (#hex|var|accent|edge|fg|reset)] ; padding [set border padding in pixels] ; palette [cycle a palette across glyphs (or `off`)] ; font [set border glyph font family (with optional size=)] ; side [set per-side glyph (top|bottom|left|right|all)] ; corner [set per-corner glyph (tl|tr|bl|br|all)] ; preset= [light | heavy | double | rounded | custom] ; font= [font family for border glyphs (use `font list` for names)] ; size= [border glyph size in points] ; color= [#hex, var(--name), accent | edge | fg, or 'reset'] ; palette= [palette name to cycle per-glyph colors, or 'off'] ; field= [frame | background | text | title] ; padding= [border-to-content padding in pixels] ; top= [side pattern: `prefix(fill)suffix` or atomic] ; bottom= [side pattern: `prefix(fill)suffix` or atomic] ; left= [side pattern: `prefix(fill)suffix` or atomic] ; right= [side pattern: `prefix(fill)suffix` or atomic] ; tl= [single corner glyph (escapes apply)] ; tr= [single corner glyph (escapes apply)] ; bl= [single corner glyph (escapes apply)] ; br= [single corner glyph (escapes apply)]",
    "show [print the resolved canvas default] ; reset [drop the canvas-level default] ; preview [stage a preview without writing the model (commit/cancel terminates)] ; preset [pick light|heavy|double|rounded|custom or `cycle`] ; color [set border color (#hex|var|accent|edge|fg|reset)] ; padding [set border padding in pixels] ; palette [cycle a palette across glyphs (or `off`)] ; font [set border glyph font family (with optional size=)] ; side [set per-side glyph (top|bottom|left|right|all)] ; corner [set per-corner glyph (tl|tr|bl|br|all)] ; preset= [light | heavy | double | rounded | custom] ; font= [font family for border glyphs (use `font list` for names)] ; size= [border glyph size in points] ; color= [#hex, var(--name), accent | edge | fg, or 'reset'] ; palette= [palette name to cycle per-glyph colors, or 'off'] ; field= [frame | background | text | title] ; padding= [border-to-content padding in pixels] ; top= [side pattern: `prefix(fill)suffix` or atomic] ; bottom= [side pattern: `prefix(fill)suffix` or atomic] ; left= [side pattern: `prefix(fill)suffix` or atomic] ; right= [side pattern: `prefix(fill)suffix` or atomic] ; tl= [single corner glyph (escapes apply)] ; tr= [single corner glyph (escapes apply)] ; bl= [single corner glyph (escapes apply)] ; br= [single corner glyph (escapes apply)]",
    "commit [write the staged preview through and clear the slot] ; cancel [discard the staged preview, no model write] ; preset= [light | heavy | double | rounded | custom] ; font= [font family for border glyphs (use `font list` for names)] ; size= [border glyph size in points] ; color= [#hex, var(--name), accent | edge | fg, or 'reset'] ; palette= [palette name to cycle per-glyph colors, or 'off'] ; field= [frame | background | text | title] ; padding= [border-to-content padding in pixels] ; top= [side pattern: `prefix(fill)suffix` or atomic] ; bottom= [side pattern: `prefix(fill)suffix` or atomic] ; left= [side pattern: `prefix(fill)suffix` or atomic] ; right= [side pattern: `prefix(fill)suffix` or atomic] ; tl= [single corner glyph (escapes apply)] ; tr= [single corner glyph (escapes apply)] ; bl= [single corner glyph (escapes apply)] ; br= [single corner glyph (escapes apply)]",
    "light [thin lines (default)] ; heavy [bold lines] ; double [double lines] ; rounded [thin lines with rounded corners] ; custom [user-supplied per-side / per-corner glyphs] ; cycle [advance to the next preset (wraps)]",
    "top ; bottom ; left ; right ; all",
    "reset [restore the slot's preset's default glyph]",
    "light [thin lines (default)] ; heavy [bold lines] ; double [double lines] ; rounded [thin lines with rounded corners] ; custom [user-supplied per-side / per-corner glyphs] ; cycle [advance to the next preset (wraps)]",
    "top ; bottom ; left ; right ; all",
    "reset [restore the slot's preset's default glyph]",
    "reset [restore the slot's preset's default glyph]",
    "from= [cap glyph at the edge's start] ; to= [cap glyph at the edge's end]",
    "arrow ; circle ; diamond ; none",
    "bg [pick a fill color on the glyph wheel] ; text [pick a text color on the glyph wheel] ; border [pick a frame color on the glyph wheel] ; pick [pick a color for the current selection] ; picker [open or close the standalone palette] ; bg= [fill / background color] ; text= [text / label color] ; border= [frame / line color] ; section= [target section index inside a multi-section node] ; range= [grapheme range A..B inside the targeted section]",
    "accent ; edge ; fg ; reset",
    "on [open the picker as a persistent standalone palette] ; off [close any open picker]",
    "section= [target section index inside a multi-section node]",
    "range= [grapheme range A..B inside the targeted section]",
    "-",
    "type= [reparent the edge or turn it into a cross link] ; display_mode= [draw the edge as a line or as a portal pair] ; reset= [drop one aspect back to its default]",
    "cross_link ; parent_child",
    "straight ; curve ; style ; position",
    "line ; portal",
    "set [pin the font family on the current selection] ; list [list every loaded font, each rendered in its face] ; size= [target on-screen size in points] ; min= [lower screen-space clamp in points] ; max= [upper screen-space clamp in points] ; section= [target section index inside a multi-section node] ; range= [grapheme range A..B inside the targeted section]",
    "set [pin the font family on the current selection] ; section= [target section index inside a multi-section node]",
    "10 ; 12 ; 14 ; 16 ; 18 ; 24 ; 32",
    "0 [\"Lord God\"] ; 1 [\"second\"]",
    "range= [grapheme range A..B inside the targeted section]",
    "-",
    "0 [\"Lord God\"] ; 1 [\"second\"]",
    "on [show the one-line FPS snapshot] ; off [hide the readout] ; debug [show the rolling per-frame average]",
    "on [show the one-line FPS snapshot] ; off [hide the readout]",
    "value= [glyph spacing: a preset or a float]",
    "tight ; normal ; wide",
    "edit [open the inline single-line editor] ; clear [drop the label text] ; text= [label text (quote multi-word values)] ; position= [anchor the label at the start, middle or end of the edge] ; position_t= [fractional position along the edge, 0.0 … 1.0] ; perpendicular= [offset away from the edge, in canvas units]",
    "start ; middle ; end",
    "-",
    "default [leave the current mode and return to Default] ; resize [enter Resize on the current selection] ; node-edit [enter NodeEdit on the selection's owning node]",
    "default [leave the current mode and return to Default]",
    "list [list the registered mutations] ; apply [run one mutation on a node] ; help [print one mutation's description] ; inspect [print one mutation's full definition]",
    "--all [include internal mutations and ones that do not target the map]",
    "-",
    "list [list the registered mutations] ; apply [run one mutation on a node] ; help [print one mutation's description] ; inspect [print one mutation's full definition]",
    "-",
    "help [List commands or print usage for one] ; anchor [Set the from/to anchor side of the selected edge] ; body [Set the body glyph of the selected edge] ; border [Configure the node border (preset, font, color, custom glyphs, palette)] ; canvas [Edit map-wide canvas defaults (border, section frame)] ; cap [Set the start/end cap glyph of the selected edge] ; color [Set bg/text/border color, or pick via the glyph wheel] ; edge [Convert edge type, switch display mode, curve/straighten, or reset style/position] ; font [Set font family / size / clamps on the selection, or list fonts] ; fps [Toggle the FPS overlay (on | off | debug)] ; spacing [Set the glyph spacing of the selected edge] ; label [Edit, clear, reposition, or offset the selected edge's label] ; mode [Change the active interaction mode (default / resize / node-edit)] ; mutation [List, apply, and inspect registered mutations] ; save [Save the current mindmap to disk] ; open [Open a mindmap file, replacing the current one] ; new [Start a new blank mindmap, replacing the current one] ; node [Resize the selected node, fit it to its content, or enter node-edit mode] ; section [Inspect, move, resize, edit text, or structurally modify a section (add / delete / split)] ; zoom [Gate the selection's rendering on camera zoom level] ; all [include commands the current selection can't use]",
    "-",
    "resize [pin the node's width and height] ; fit [shrink the node to its content] ; edit [enter node-edit mode on the selection]",
    "resize [pin the node's width and height]",
    "-",
    "-",
    "-",
    "move [shift section offset (dx/dy delta or x/y absolute)] ; resize [pin section size (w/h) or clear to fill-parent] ; show [print the resolved per-section properties] ; text [replace section text (runs=preserve|clear)] ; edit [open the section text editor on the resolved target] ; add [insert a new section] ; delete [remove the section (errors when only one remains)] ; split [split a section in two at a grapheme boundary] ; frame [configure the section's frame border (subverb tree)]",
    "move [shift section offset (dx/dy delta or x/y absolute)]",
    "dx= [relative move along x axis (canvas units)] ; dy= [relative move along y axis (canvas units)] ; x= [absolute x offset within parent node] ; y= [absolute y offset within parent node] ; section= [target section index inside a multi-section node]",
    "fill [clear the size pin and fill the parent node] ; w= [section width (canvas units)] ; h= [section height (canvas units)] ; section= [target section index inside a multi-section node]",
    "section= [target section index inside a multi-section node]",
    "text= [section text payload (quote multi-word values)] ; runs= [preserve|clear — keep or drop per-grapheme styling] ; section= [target section index inside a multi-section node]",
    "at= [insertion / split index] ; text= [section text payload (quote multi-word values)]",
    "at= [insertion / split index] ; section= [target section index inside a multi-section node]",
    "section= [target section index inside a multi-section node]",
    "section= [target section index inside a multi-section node]",
    "section= [target section index inside a multi-section node]",
    "0 [\"Lord God\"] ; 1 [\"second\"]",
    "preserve [keep per-grapheme styling where the new text supports it] ; clear [drop every prior run and inherit the first one's style]",
    "show [print the resolved section-frame style] ; reset [drop the per-section override] ; preview [stage a preview without writing the model (commit/cancel terminates)] ; preset= [light | heavy | double | rounded | custom] ; font= [font family for border glyphs (use `font list` for names)] ; size= [border glyph size in points] ; color= [#hex, var(--name), accent | edge | fg, or 'reset'] ; palette= [palette name to cycle per-glyph colors, or 'off'] ; field= [frame | background | text | title] ; padding= [border-to-content padding in pixels] ; top= [side pattern: `prefix(fill)suffix` or atomic] ; bottom= [side pattern: `prefix(fill)suffix` or atomic] ; left= [side pattern: `prefix(fill)suffix` or atomic] ; right= [side pattern: `prefix(fill)suffix` or atomic] ; tl= [single corner glyph (escapes apply)] ; tr= [single corner glyph (escapes apply)] ; bl= [single corner glyph (escapes apply)] ; br= [single corner glyph (escapes apply)] ; section= [target section index inside a multi-section node]",
    "light [thin lines (default)] ; heavy [bold lines] ; double [double lines] ; rounded [thin lines with rounded corners] ; custom [user-supplied per-side / per-corner glyphs]",
    "commit [write the staged preview through and clear the slot] ; cancel [discard the staged preview, no model write] ; preset= [light | heavy | double | rounded | custom] ; font= [font family for border glyphs (use `font list` for names)] ; size= [border glyph size in points] ; color= [#hex, var(--name), accent | edge | fg, or 'reset'] ; palette= [palette name to cycle per-glyph colors, or 'off'] ; field= [frame | background | text | title] ; padding= [border-to-content padding in pixels] ; top= [side pattern: `prefix(fill)suffix` or atomic] ; bottom= [side pattern: `prefix(fill)suffix` or atomic] ; left= [side pattern: `prefix(fill)suffix` or atomic] ; right= [side pattern: `prefix(fill)suffix` or atomic] ; tl= [single corner glyph (escapes apply)] ; tr= [single corner glyph (escapes apply)] ; bl= [single corner glyph (escapes apply)] ; br= [single corner glyph (escapes apply)] ; section= [target section index inside a multi-section node]",
    "-",
    "section= [target section index inside a multi-section node]",
    "0 [\"Lord God\"] ; 1 [\"second\"]",
    "0 [\"Lord God\"] ; 1 [\"second\"]",
    "clear [drop both bounds so the selection always renders] ; min= [lower inclusive zoom bound (or `unset`)] ; max= [upper inclusive zoom bound (or `unset`)]",
    "clear [drop both bounds so the selection always renders]",
    "0.25 ; 0.5 ; 1.0 ; 1.5 ; 2.0 ; 3.0 ; 5.0 ; unset [remove the bound]",
    "0.25 ; 0.5 ; 1.0 ; 1.5 ; 2.0 ; 3.0 ; 5.0 ; unset [remove the bound]",
    "preview [stage a preview without writing the model (commit/cancel terminates)] ; preset [pick light|heavy|double|rounded|custom or `cycle`]",
    "heavy [bold lines]",
    "coral ; coral-v3",
    "off [clear the font override]",
    "reset [restore the slot's preset's default glyph]",
    "verbose [surface the dual color cascade (frame_color vs border.color)]",
    "commit [write the staged preview through and clear the slot]",
    "focused [target the focused section's frame rather than the unfocused default] ; font [set border glyph font family (with optional size=)]",
    "on [open the picker as a persistent standalone palette] ; off [close any open picker]",
    "set [pin the font family on the current selection]",
    "on [show the one-line FPS snapshot] ; off [hide the readout]",
    "clear [drop the label text]",
    "default [leave the current mode and return to Default]",
    "list [list the registered mutations]",
    "resize [pin the node's width and height]",
    "show [print the resolved section-frame style] ; reset [drop the per-section override] ; preview [stage a preview without writing the model (commit/cancel terminates)] ; preset= [light | heavy | double | rounded | custom] ; font= [font family for border glyphs (use `font list` for names)] ; size= [border glyph size in points] ; color= [#hex, var(--name), accent | edge | fg, or 'reset'] ; palette= [palette name to cycle per-glyph colors, or 'off'] ; field= [frame | background | text | title] ; padding= [border-to-content padding in pixels] ; top= [side pattern: `prefix(fill)suffix` or atomic] ; bottom= [side pattern: `prefix(fill)suffix` or atomic] ; left= [side pattern: `prefix(fill)suffix` or atomic] ; right= [side pattern: `prefix(fill)suffix` or atomic] ; tl= [single corner glyph (escapes apply)] ; tr= [single corner glyph (escapes apply)] ; bl= [single corner glyph (escapes apply)] ; br= [single corner glyph (escapes apply)] ; section= [target section index inside a multi-section node]",
    "commit [write the staged preview through and clear the slot] ; cancel [discard the staged preview, no model write] ; preset= [light | heavy | double | rounded | custom] ; font= [font family for border glyphs (use `font list` for names)] ; size= [border glyph size in points] ; color= [#hex, var(--name), accent | edge | fg, or 'reset'] ; palette= [palette name to cycle per-glyph colors, or 'off'] ; field= [frame | background | text | title] ; padding= [border-to-content padding in pixels] ; top= [side pattern: `prefix(fill)suffix` or atomic] ; bottom= [side pattern: `prefix(fill)suffix` or atomic] ; left= [side pattern: `prefix(fill)suffix` or atomic] ; right= [side pattern: `prefix(fill)suffix` or atomic] ; tl= [single corner glyph (escapes apply)] ; tr= [single corner glyph (escapes apply)] ; bl= [single corner glyph (escapes apply)] ; br= [single corner glyph (escapes apply)] ; section= [target section index inside a multi-section node]",
    "all [include commands the current selection can't use]",
    "clear [drop both bounds so the selection always renders]",
    "-",
];
