// SPDX-License-Identifier: MPL-2.0

//! Pinned oracle signatures — the exact console behavior at the
//! time each row was recorded. Generated once from a run of the
//! corpus and then hand-owned: a row changes only when a change to
//! the console is *meant* to change what a user sees, and the diff
//! in the failure output is the review surface for that decision.
//!
//! Rows are positional — index N here answers input N in the
//! matching corpus in [`super::oracle_corpus`].

pub const EXEC_EXPECTED: &[&str] = &[
    "LINES commands (use `help all` to see non-applicable ones):\\n  help         List commands or print usage for one\\n  border       Configure the node border (preset, font, color, custom glyphs, palette)\\n  canvas       Edit map-wide canvas defaults (border, section frame)\\n  color        Set bg/text/border color, or pick via the glyph wheel\\n  font         Set font family / size / clamps on the selection, or list fonts\\n  fps          Toggle the FPS overlay (on | off | debug)\\n  mode         Change the active interaction mode (default / resize / node-edit)\\n  mutation     List, apply, and inspect registered mutations\\n  save         Save the current mindmap to disk\\n  open         Open a mindmap file, replacing the current one\\n  new          Start a new blank mindmap, replacing the current one\\n  node         Resize the selected node, fit it to its content, or enter node-edit mode\\n  section      Inspect, move, resize, edit text, or structurally modify a section (add / delete / split)\\n  zoom         Gate the selection's rendering on camera zoom level",
    "LINES all commands:\\n  help         List commands or print usage for one\\n  anchor       Set the from/to anchor side of the selected edge\\n  body         Set the body glyph of the selected edge\\n  border       Configure the node border (preset, font, color, custom glyphs, palette)\\n  canvas       Edit map-wide canvas defaults (border, section frame)\\n  cap          Set the start/end cap glyph of the selected edge\\n  color        Set bg/text/border color, or pick via the glyph wheel\\n  edge         Convert edge type, switch display mode, curve/straighten, or reset style/position\\n  font         Set font family / size / clamps on the selection, or list fonts\\n  fps          Toggle the FPS overlay (on | off | debug)\\n  spacing      Set the glyph spacing of the selected edge\\n  label        Edit, clear, reposition, or offset the selected edge's label\\n  mode         Change the active interaction mode (default / resize / node-edit)\\n  mutation     List, apply, and inspect registered mutations\\n  save         Save the current mindmap to disk\\n  open         Open a mindmap file, replacing the current one\\n  new          Start a new blank mindmap, replacing the current one\\n  node         Resize the selected node, fit it to its content, or enter node-edit mode\\n  section      Inspect, move, resize, edit text, or structurally modify a section (add / delete / split)\\n  zoom         Gate the selection's rendering on camera zoom level",
    "LINES color — Set bg/text/border color, or pick via the glyph wheel\\nusage: color bg=<color> text=<color> border=<color> [section=<N>] [range=<A..B>]\\n       color bg|text|border|pick\\n       color picker on|off\\ntags: color, bg, text, border, section, range, pick, picker, wheel",
    "LINES font — Set font family / size / clamps on the selection, or list fonts\\nusage: font set <family> [section=<N>] [range=<A..B>]\\n       font list\\n       font size=<pt> [min=<pt>] [max=<pt>] [section=<N>] [range=<A..B>]\\ntags: font, family, set, list, size, min, max, clamp, pt, smaller, larger, section, range",
    "ERR unknown command: nope",
    "ERR usage: anchor from=<side> to=<side>",
    "OK anchor applied",
    "LINES to already bottom",
    "ERR 'diagonal': expected auto|top|right|bottom|left",
    "ERR unknown key 'bogus'",
    "ERR no edge selected",
    "ERR usage: body glyph=<dot|dash|double|wave|chain>",
    "OK body glyph set to dash",
    "ERR glyph 'nope' must be one of dot|dash|double|wave|chain",
    "ERR usage: body glyph=<dot|dash|double|wave|chain>",
    "ERR usage: border on|off|show|reset | border <key>=<value> …",
    "OK border on on 1 node(s)",
    "OK border: already off",
    "OK border toggled → on",
    "ERR border show: side='nope' unknown; pick top | bottom | left | right | all",
    "OK border: no change",
    "ERR border: unknown subverb 'nope'\\n  visibility: on | off | toggle | reset\\n  readout:    show [side=…] [verbose]\\n  per-field:  preset | color | padding | palette | font\\n  glyphs:     side <which> <pattern|reset> | corner <which> <glyph|reset>\\n  staged:     preview <kv>=… | preview commit | preview cancel\\n  composed:   <key>=<value> [<key>=<value> …]",
    "OK border applied to 1 node(s)",
    "ERR preset 'nope' unknown; pick one of light | heavy | double | rounded | custom | cycle",
    "LINES border preset → 'heavy' (cycle)\\nborder applied to 1 node(s)",
    "ERR usage: border preset <light|heavy|double|rounded|custom|cycle>",
    "OK border applied to 1 node(s)",
    "ERR usage: border color <#hex|var(--name)|preset|reset>",
    "OK border applied to 1 node(s)",
    "ERR padding='abc' is not a number",
    "ERR usage: border padding <px>",
    "OK border applied to 1 node(s)",
    "ERR usage: border palette <name|off> [field=<frame|background|text|title>]",
    "OK border applied to 1 node(s)",
    "ERR usage: border font <family|off> [size=<pt>]",
    "OK border applied to 1 node(s)",
    "ERR border side: 'nope' unknown; pick top | bottom | left | right | all",
    "ERR border side top: missing pattern (or 'reset' to clear)",
    "ERR usage: border side <top|bottom|left|right|all> <pattern|reset>",
    "OK border applied to 1 node(s)",
    "ERR border corner: 'nope' unknown; pick tl | tr | bl | br | all",
    "ERR border corner tl: missing glyph (or 'reset' to clear)",
    "ERR usage: border corner <tl|tr|bl|br|all> <glyph|reset>",
    "OK border applied to 1 node(s)",
    "OK border applied to 1 node(s)",
    "ERR size='abc' is not a number",
    "ERR unknown key 'bogus'; valid keys: preset | font | size | color | palette | field | padding | top | bottom | left | right | tl | tr | bl | br",
    "OK border preview active (commit / cancel to terminate)",
    "OK border preview: no active preview",
    "OK border preview: no active preview",
    "ERR border preview: unknown subverb 'nope'; use 'commit', 'cancel', or kv form",
    "ERR usage: border preview <key>=<value> … | border preview commit | border preview cancel",
    "ERR border: not applicable to edges",
    "ERR usage: canvas border|section-frame [focused] show|reset|<key>=<value> …",
    "ERR canvas: unknown subverb 'nope'; use 'border' or 'section-frame'",
    "ERR usage: canvas border show|reset|<key>=<value> …",
    "LINES canvas border: (no map-wide default — every framed node falls back to its per-node `style.frame_color` / hardcoded glyph defaults)",
    "OK canvas border: no change",
    "OK canvas border updated",
    "ERR preset 'nope' unknown; pick one of light | heavy | double | rounded | custom | cycle",
    "ERR canvas border: unknown subverb 'nope'; use 'show', 'reset', 'preview', 'preset', 'color', 'padding', 'palette', 'font', 'side', 'corner', or kv form",
    "ERR unknown key 'bogus'; valid keys: preset | font | size | color | palette | field | padding | top | bottom | left | right | tl | tr | bl | br",
    "OK canvas border updated",
    "ERR padding='abc' is not a number",
    "OK canvas border updated",
    "OK canvas border updated",
    "ERR canvas border corner: 'nope' unknown; pick tl | tr | bl | br | all",
    "ERR canvas border: unexpected positional 'preset' alongside a kv pair — did you mean to quote a multi-word value? e.g. `canvas border palette=\"preset\"`",
    "ERR usage: canvas section-frame [focused] show|reset|<key>=<value> …",
    "LINES canvas section-frame: (no map-wide default — falls back to hardcoded light floor)",
    "OK canvas section-frame: no change",
    "ERR canvas section-frame: unknown subverb 'nope'; use 'show', 'reset', 'preview', 'preset', 'color', 'padding', 'palette', 'font', 'side', 'corner', or kv form",
    "LINES canvas section-frame focused: (no map-wide default — falls back to hardcoded heavy floor)",
    "OK canvas section-frame focused: no change",
    "ERR canvas section-frame focused: unknown subverb 'nope'; use 'show', 'reset', 'preview', 'preset', 'color', 'padding', 'palette', 'font', 'side', 'corner', or kv form",
    "OK canvas section-frame updated",
    "OK canvas section-frame focused updated",
    "OK canvas border preview: no active preview",
    "OK canvas border preview: no active preview",
    "ERR canvas border preview: unknown subverb 'nope'; use 'commit', 'cancel', or kv form",
    "ERR usage: cap from=<name> to=<name>",
    "OK cap applied",
    "LINES cap to already none",
    "ERR 'nope': expected arrow|circle|diamond|none",
    "ERR unknown key 'bogus'",
    "ERR usage: color bg|text|border[=<color>]   |   color pick",
    "OK color applied",
    "ERR bg: unknown color 'nope'",
    "ERR bogus: unknown color '1'",
    "OK ",
    "OK ",
    "OK ",
    "OK ",
    "OK ",
    "OK ",
    "ERR usage: color picker on | color picker off",
    "ERR usage: color picker on | color picker off",
    "ERR usage: color bg|text|border[=<color>]   |   color pick",
    "ERR color bg: not applicable to a section (section-level chrome doesn't exist)",
    "ERR bg: not applicable to a section (section-level chrome doesn't exist)",
    "ERR color: section='abc' is not a non-negative integer",
    "OK color applied to section 0 range 0..2",
    "ERR color: range=A..B requires section=N — ranges target grapheme indices inside one section",
    "ERR color: range='zz' — expected `start..end` (e.g. `range=2..7`)",
    "ERR usage: edge type=<...>   |   edge display_mode=<...>   |   edge reset=<straight|curve|style|position>",
    "OK edge applied",
    "ERR type 'nope' must be cross_link or parent_child",
    "ERR connection already straight",
    "ERR reset 'nope' must be straight, curve, style, or position",
    "OK edge applied",
    "ERR display_mode 'nope' must be line or portal",
    "ERR unknown key 'bogus'",
    "ERR usage: font set <family> | font list | font size=<pt> [min=<pt>] [max=<pt>]",
    "ERR usage: font set <family> [section=N] [range=A..B]",
    "ERR font: 'NoSuchFamilyHere' is not a loaded font; try `font list`",
    "ERR font: unknown subverb 'nope'; use 'set <family>', 'list', or 'size=<pt>' (kv form)",
    "OK font applied",
    "ERR size='abc' is not a number",
    "ERR size='0' must be positive and finite; got 0",
    "ERR unknown key 'bogus'",
    "ERR font: min=8 > max=4 (inverted bounds)",
    "ERR font: range=A..B requires section=N — ranges target grapheme indices inside one section",
    "OK font applied to section 0 range 0..2",
    "ERR font: range='zz' — expected `start..end` (e.g. `range=2..7`)",
    "ERR font: section='abc' is not a non-negative integer",
    "ERR min/max: sections have no screen-space clamps",
    "ERR usage: fps on | fps off | fps debug",
    "OK ",
    "OK ",
    "OK ",
    "ERR usage: fps on | fps off | fps debug",
    "ERR usage: spacing value=<tight|normal|wide | <float>>",
    "OK spacing set to tight",
    "OK spacing set to 3.5",
    "ERR 'nope' must be a preset (tight|normal|wide) or a float",
    "ERR usage: spacing value=<tight|normal|wide | <float>>",
    "ERR usage: label text=\"<text>\" [position=<start|middle|end>]",
    "ERR no edge selected",
    "OK label applied",
    "OK label applied",
    "ERR position 'nope' must be start|middle|end",
    "ERR position_t already ≈ 0.5000",
    "ERR position_t 'abc' is not a number",
    "OK label applied",
    "ERR unknown key 'bogus'",
    "ERR unknown label verb 'nope'; use kv form (text=... position=...) or 'edit' / 'clear'",
    "ERR usage: mode default | mode resize | mode node-edit",
    "OK mode: returning to Default",
    "OK entering resize mode",
    "OK entering node-edit mode on '0'",
    "ERR mode: unknown subverb 'nope'; use 'default', 'resize', or 'node-edit'",
    "ERR mutation needs a sub-command (list / apply / help / inspect)",
    "OK no mutations registered",
    "OK no mutations registered",
    "ERR mutation apply needs an id (`mutation apply <id>`)",
    "ERR unknown mutation: no-such-mutation",
    "ERR mutation help needs an id",
    "ERR unknown mutation: no-such-mutation",
    "ERR mutation inspect needs an id",
    "ERR unknown mutation: no-such-mutation",
    "ERR unknown mutation sub-command: nope (try list / apply / help / inspect)",
    "ERR usage: node resize <w> <h> | node fit | node edit",
    "OK node '0' fitted to content",
    "OK entering node-edit mode on '0'",
    "ERR node resize: <w> must be a number",
    "OK node '0' resized to 120×60",
    "ERR node resize: <w> must be a number",
    "ERR node: unknown subverb 'nope'",
    "ERR usage: open <path>",
    "ERR no file path bound; use `save <path>` to choose one",
    "OK new map (no file path; use `save <path>` to bind one)",
    "ERR usage: section move dx=<f64> dy=<f64> | section move x=<f64> y=<f64> | section resize w=<f64> h=<f64> | section resize fill | section show | section text \"<text>\" | section add | section delete | section split | section frame …",
    "ERR section: node '0' has 2 sections — pick one (click) or pass section=<idx>",
    "ERR section: unknown subverb 'nope'\\n  readout:   show\\n  text:      text \"<text>\" [runs=preserve|clear]\\n  geometry:  move dx=… dy=… | move x=… y=… | resize w=… h=… | resize fill\\n  structure: add | delete | split\\n  subject:   frame …  (per-section frame border)\\n  editor:    edit",
    "ERR section: node '0' has 2 sections — pick one (click) or pass section=<idx>",
    "ERR section[0] extends past node right edge (201 > 200)",
    "ERR section move: cannot mix delta form (dx/dy) and absolute form (x/y) — pick one",
    "ERR section[0] extends past node right edge (201 > 200)",
    "ERR section move: dx='abc' is not a number",
    "ERR section move: unknown key 'bogus'; use dx|dy|x|y|section",
    "OK section: no change",
    "OK section[0] resized",
    "ERR usage: section resize w=<f64> h=<f64> | section resize fill [section=<idx>]",
    "ERR section resize: unknown key 'bogus'; use w|h|section",
    "OK section[0] text replaced (runs preserved)",
    "OK section[0] text replaced (runs cleared)",
    "ERR section text: runs='nope' not recognized; use 'preserve' or 'clear'",
    "ERR section text: unknown key 'bogus'; use text|runs|section",
    "OK section[2] added on node '0'",
    "OK section[0] added on node '0'",
    "ERR section add: at='abc' is not a non-negative integer",
    "ERR section add: unknown key 'bogus'; use at|text",
    "OK section[0] deleted from node '0'",
    "ERR section delete: unknown key 'bogus'; use section",
    "ERR section split: at=<grapheme> required — pass an integer grapheme index (use `section show` to see the current section's grapheme count); split-at-end-of-text (the prior default) silently created an empty suffix section",
    "OK section[0] split — new section at index 1",
    "ERR section split: at='abc' is not a non-negative integer",
    "ERR section split: unknown key 'bogus'; use at|section",
    "ERR section: node '0' has 2 sections — pick one (click) or pass section=<idx>",
    "ERR section[99] not found on node '0'",
    "ERR section: section='abc' is not a non-negative integer",
    "OK opening editor on section[0]…",
    "ERR section edit: unknown key 'bogus'; use section",
    "ERR usage: section frame show|reset | section frame <key>=<value> … [section=<idx>]",
    "LINES section frame: node='0' section=0\\n  [unfocused]\\n    source:    hardcoded light floor\\n    preset:    light\\n    font:      (default)\\n    size:      10 pt\\n    color:     #00E5FF\\n    palette:   (none)\\n    glyphs:    (preset 'light' defaults)\\n  [focused]\\n    source:    hardcoded heavy floor\\n    preset:    heavy\\n    font:      (default)\\n    size:      10 pt\\n    color:     #00E5FF\\n    palette:   (none)\\n    glyphs:    (preset 'heavy' defaults)",
    "OK section frame: no change",
    "ERR section frame: unknown subverb 'nope'\\n  positional today: show | reset | preview\\n  per-field grammar lives in the kv form for now — `section frame preset=heavy padding=8` etc. Per-node `border` and `canvas border` accept positional `preset / color / padding / palette / font / side / corner`; section-frame parity is tracked as a follow-up.\\n  staged: preview <kv>=… | preview commit | preview cancel\\n  composed: <key>=<value> [<key>=<value> …]",
    "OK section frame applied to 1 section(s)",
    "ERR unknown key 'bogus'; valid keys: preset | font | size | color | palette | field | padding | top | bottom | left | right | tl | tr | bl | br",
    "OK section frame preview active (commit / cancel to terminate)",
    "OK section frame preview: no active preview",
    "OK section frame preview: no active preview",
    "ERR section frame preview: unknown subverb 'nope'; use 'commit', 'cancel', or kv form",
    "OK section frame applied to 1 section(s)",
    "ERR section frame: section='abc' is not a non-negative integer",
    "LINES section[0] of node \"0\"\\n  text:     \"Lord God\"\\n  runs:     1 runs (flags: 1 bold, 0 italic, 1 underline, 0 hyperlink)\\n  offset:   (0.0, 0.0)\\n  size:     None [fill parent: 373.5 × 109.0]\\n  channel:  None [→ index 0]\\n  bindings: 0 triggers\\n  frame:    (falls back to canvas default / floor)",
    "ERR section: requires a node or section selection",
    "ERR section: requires a node or section selection",
    "OK border on on 2 node(s)",
    "LINES font: applied to 2 node(s)",
    "LINES min/max: nodes have no screen-space clamps",
    "OK color applied",
    "ERR usage: zoom [min=<zoom|unset>] [max=<zoom|unset>]   |   zoom clear",
    "OK zoom: no change on node",
    "OK zoom applied to node",
    "OK zoom: no change on node",
    "ERR min='abc' is not a number or `unset`",
    "ERR min='0' must be positive and finite or `unset`; got 0",
    "ERR zoom: min=2 > max=1 (inverted bounds)",
    "ERR unknown key 'bogus'",
    "ERR unknown verb 'nope' — usage: zoom [min=<zoom|unset>] [max=<zoom|unset>]   |   zoom clear",
    "ERR zoom: no selection",
];

/// Prefixes, not whole signatures — see
/// [`super::oracle_corpus::EXEC_PREFIX_CORPUS`] for which two
/// kinds of host-dependent tail are cut off and why.
pub const EXEC_PREFIX_EXPECTED: &[&str] = &[
    "LINES visible: off  (toggle: `border toggle`)\\npreset:  (default)  (cycle: `border preset cycle`)\\nfont:    (default) (14 pt)  (override: `border font <family>`, source: hardcoded floor)\\ncolor:   #30b082\\npalette: (none)\\npadding: 4 px",
    "LINES visible: off  (toggle: `border toggle`)\\npreset:  (default)  (cycle: `border preset cycle`)\\nfont:    (default) (14 pt)  (override: `border font <family>`, source: hardcoded floor)\\ncolor (cascade):\\n  style.frame_color    = #30b082          # set via `color border=`\\n  style.border.color   = (unset) [→ #30b082]   # set via `border color`\\npalette: (none)\\npadding: 4 px",
    "LINES visible: off  (toggle: `border toggle`)\\npreset:  (default)  (cycle: `border preset cycle`)\\nfont:    (default) (14 pt)  (override: `border font <family>`, source: hardcoded floor)\\ncolor:   #30b082\\npalette: (none)\\npadding: 4 px",
    "ERR open /nonexistent-dir-xyz/x.mindmap.json: Failed to read file /nonexistent-dir-xyz/x.mindmap.json:",
];

pub const COMPLETION_EXPECTED: &[&str] = &[
    "help [List commands or print usage for one] ; border [Configure the node border (preset, font, color, custom glyphs, palette)] ; canvas [Edit map-wide canvas defaults (border, section frame)] ; color [Set bg/text/border color, or pick via the glyph wheel] ; font [Set font family / size / clamps on the selection, or list fonts] ; fps [Toggle the FPS overlay (on | off | debug)] ; mode [Change the active interaction mode (default / resize / node-edit)] ; mutation [List, apply, and inspect registered mutations] ; save [Save the current mindmap to disk] ; open [Open a mindmap file, replacing the current one] ; new [Start a new blank mindmap, replacing the current one] ; node [Resize the selected node, fit it to its content, or enter node-edit mode] ; section [Inspect, move, resize, edit text, or structurally modify a section (add / delete / split)] ; zoom [Gate the selection's rendering on camera zoom level]",
    "color [Set bg/text/border color, or pick via the glyph wheel]",
    "body [Set the body glyph of the selected edge]",
    "help [List commands or print usage for one] ; anchor [Set the from/to anchor side of the selected edge] ; body [Set the body glyph of the selected edge] ; border [Configure the node border (preset, font, color, custom glyphs, palette)] ; canvas [Edit map-wide canvas defaults (border, section frame)] ; cap [Set the start/end cap glyph of the selected edge] ; color [Set bg/text/border color, or pick via the glyph wheel] ; edge [Convert edge type, switch display mode, curve/straighten, or reset style/position] ; font [Set font family / size / clamps on the selection, or list fonts] ; fps [Toggle the FPS overlay (on | off | debug)] ; spacing [Set the glyph spacing of the selected edge] ; label [Edit, clear, reposition, or offset the selected edge's label] ; mode [Change the active interaction mode (default / resize / node-edit)] ; mutation [List, apply, and inspect registered mutations] ; save [Save the current mindmap to disk] ; open [Open a mindmap file, replacing the current one] ; new [Start a new blank mindmap, replacing the current one] ; node [Resize the selected node, fit it to its content, or enter node-edit mode] ; section [Inspect, move, resize, edit text, or structurally modify a section (add / delete / split)] ; zoom [Gate the selection's rendering on camera zoom level] ; all [include commands the current selection can't use]",
    "color [Set bg/text/border color, or pick via the glyph wheel]",
    "anchor [Set the from/to anchor side of the selected edge] ; all [include commands the current selection can't use]",
    "from= ; to=",
    "from=",
    "auto ; top ; right ; bottom ; left",
    "top",
    "glyph=",
    "dot ; dash ; double ; wave ; chain",
    "dot ; dash ; double",
    "on [show the border] ; off [hide the border] ; toggle [flip show_frame per node] ; show [print the resolved config (use [side=…] [verbose])] ; reset [drop the per-node override] ; preview [stage a preview without writing the model (commit/cancel terminates)] ; preset [pick light|heavy|double|rounded|custom or `cycle`] ; color [set border color (#hex|var|preset|reset)] ; padding [set border padding in pixels] ; palette [cycle a palette across glyphs (or `off`)] ; font [set border glyph font family (with optional size=)] ; side [set per-side glyph (top|bottom|left|right|all)] ; corner [set per-corner glyph (tl|tr|bl|br|all)] ; preset= [light | heavy | double | rounded | custom] ; font= [font family for border glyphs (use `font list` for names)] ; size= [border glyph size in points] ; color= [#hex, var(--name), preset, or 'reset'] ; palette= [palette name to cycle per-glyph colors, or 'off'] ; field= [frame | background | text | title] ; padding= [border-to-content padding in pixels] ; top= [side pattern: `prefix(fill)suffix` or atomic] ; bottom= [side pattern: `prefix(fill)suffix` or atomic] ; left= [side pattern: `prefix(fill)suffix` or atomic] ; right= [side pattern: `prefix(fill)suffix` or atomic] ; tl= [single corner glyph (escapes apply)] ; tr= [single corner glyph (escapes apply)] ; bl= [single corner glyph (escapes apply)] ; br= [single corner glyph (escapes apply)]",
    "preview [stage a preview without writing the model (commit/cancel terminates)] ; preset [pick light|heavy|double|rounded|custom or `cycle`] ; preset= [light | heavy | double | rounded | custom]",
    "light [thin lines (default)] ; heavy [bold lines] ; double [double lines] ; rounded [thin lines with rounded corners] ; custom [user-supplied per-side / per-corner glyphs] ; cycle [advance to the next preset (wraps)]",
    "heavy [bold lines]",
    "accent ; edge ; fg ; reset",
    "My Palette ; autumn ; coral ; coral-v3 ; mountain ; navy-v3 ; rainbow ; rocky ; sandy ; stars-v3 ; summer ; sweet ; off [clear palette cycling]",
    "top ; bottom ; left ; right ; all",
    "reset [restore the slot's preset's default glyph]",
    "tl ; tr ; bl ; br ; all",
    "reset [restore the slot's preset's default glyph]",
    "side= [filter readout to one side (top|bottom|left|right|all)] ; verbose [surface the dual color cascade (frame_color vs border.color)]",
    "top ; bottom ; left ; right ; all",
    "commit [write the staged preview through and clear the slot] ; cancel [discard the staged preview, no model write] ; preset= [light | heavy | double | rounded | custom] ; font= [font family for border glyphs (use `font list` for names)] ; size= [border glyph size in points] ; color= [#hex, var(--name), preset, or 'reset'] ; palette= [palette name to cycle per-glyph colors, or 'off'] ; field= [frame | background | text | title] ; padding= [border-to-content padding in pixels] ; top= [side pattern: `prefix(fill)suffix` or atomic] ; bottom= [side pattern: `prefix(fill)suffix` or atomic] ; left= [side pattern: `prefix(fill)suffix` or atomic] ; right= [side pattern: `prefix(fill)suffix` or atomic] ; tl= [single corner glyph (escapes apply)] ; tr= [single corner glyph (escapes apply)] ; bl= [single corner glyph (escapes apply)] ; br= [single corner glyph (escapes apply)]",
    "-",
    "light [thin lines (default)] ; heavy [bold lines] ; double [double lines] ; rounded [thin lines with rounded corners] ; custom [user-supplied per-side / per-corner glyphs] ; cycle [advance to the next preset (wraps)]",
    "light [thin lines (default)] ; heavy [bold lines] ; double [double lines] ; rounded [thin lines with rounded corners] ; custom [user-supplied per-side / per-corner glyphs] ; cycle [advance to the next preset (wraps)]",
    "frame ; background ; text ; title",
    "-",
    "-",
    "-",
    "border ; section-frame",
    "border",
    "show ; reset ; preview ; preset ; color ; padding ; palette ; font ; side ; corner ; preset= [light | heavy | double | rounded | custom] ; font= [font family for border glyphs (use `font list` for names)] ; size= [border glyph size in points] ; color= [#hex, var(--name), preset, or 'reset'] ; palette= [palette name to cycle per-glyph colors, or 'off'] ; field= [frame | background | text | title] ; padding= [border-to-content padding in pixels] ; top= [side pattern: `prefix(fill)suffix` or atomic] ; bottom= [side pattern: `prefix(fill)suffix` or atomic] ; left= [side pattern: `prefix(fill)suffix` or atomic] ; right= [side pattern: `prefix(fill)suffix` or atomic] ; tl= [single corner glyph (escapes apply)] ; tr= [single corner glyph (escapes apply)] ; bl= [single corner glyph (escapes apply)] ; br= [single corner glyph (escapes apply)]",
    "preview ; preset ; preset= [light | heavy | double | rounded | custom]",
    "light [thin lines (default)] ; heavy [bold lines] ; double [double lines] ; rounded [thin lines with rounded corners] ; custom [user-supplied per-side / per-corner glyphs] ; cycle [advance to the next preset (wraps)]",
    "commit [write the staged preview through and clear the slot] ; cancel [discard the staged preview, no model write] ; preset= [light | heavy | double | rounded | custom] ; font= [font family for border glyphs (use `font list` for names)] ; size= [border glyph size in points] ; color= [#hex, var(--name), preset, or 'reset'] ; palette= [palette name to cycle per-glyph colors, or 'off'] ; field= [frame | background | text | title] ; padding= [border-to-content padding in pixels] ; top= [side pattern: `prefix(fill)suffix` or atomic] ; bottom= [side pattern: `prefix(fill)suffix` or atomic] ; left= [side pattern: `prefix(fill)suffix` or atomic] ; right= [side pattern: `prefix(fill)suffix` or atomic] ; tl= [single corner glyph (escapes apply)] ; tr= [single corner glyph (escapes apply)] ; bl= [single corner glyph (escapes apply)] ; br= [single corner glyph (escapes apply)]",
    "light [thin lines (default)] ; heavy [bold lines] ; double [double lines] ; rounded [thin lines with rounded corners] ; custom [user-supplied per-side / per-corner glyphs] ; cycle [advance to the next preset (wraps)]",
    "-",
    "accent ; edge ; fg ; reset",
    "My Palette ; autumn ; coral ; coral-v3 ; mountain ; navy-v3 ; rainbow ; rocky ; sandy ; stars-v3 ; summer ; sweet ; off [clear palette cycling]",
    "-",
    "top ; bottom ; left ; right ; all",
    "reset [restore the slot's preset's default glyph]",
    "tl ; tr ; bl ; br ; all",
    "reset [restore the slot's preset's default glyph]",
    "-",
    "reset [restore the slot's preset's default glyph]",
    "focused ; show ; reset ; preview ; preset ; color ; padding ; palette ; font ; side ; corner ; preset= [light | heavy | double | rounded | custom] ; font= [font family for border glyphs (use `font list` for names)] ; size= [border glyph size in points] ; color= [#hex, var(--name), preset, or 'reset'] ; palette= [palette name to cycle per-glyph colors, or 'off'] ; field= [frame | background | text | title] ; padding= [border-to-content padding in pixels] ; top= [side pattern: `prefix(fill)suffix` or atomic] ; bottom= [side pattern: `prefix(fill)suffix` or atomic] ; left= [side pattern: `prefix(fill)suffix` or atomic] ; right= [side pattern: `prefix(fill)suffix` or atomic] ; tl= [single corner glyph (escapes apply)] ; tr= [single corner glyph (escapes apply)] ; bl= [single corner glyph (escapes apply)] ; br= [single corner glyph (escapes apply)]",
    "show ; reset ; preview ; preset ; color ; padding ; palette ; font ; side ; corner ; preset= [light | heavy | double | rounded | custom] ; font= [font family for border glyphs (use `font list` for names)] ; size= [border glyph size in points] ; color= [#hex, var(--name), preset, or 'reset'] ; palette= [palette name to cycle per-glyph colors, or 'off'] ; field= [frame | background | text | title] ; padding= [border-to-content padding in pixels] ; top= [side pattern: `prefix(fill)suffix` or atomic] ; bottom= [side pattern: `prefix(fill)suffix` or atomic] ; left= [side pattern: `prefix(fill)suffix` or atomic] ; right= [side pattern: `prefix(fill)suffix` or atomic] ; tl= [single corner glyph (escapes apply)] ; tr= [single corner glyph (escapes apply)] ; bl= [single corner glyph (escapes apply)] ; br= [single corner glyph (escapes apply)]",
    "commit [write the staged preview through and clear the slot] ; cancel [discard the staged preview, no model write] ; preset= [light | heavy | double | rounded | custom] ; font= [font family for border glyphs (use `font list` for names)] ; size= [border glyph size in points] ; color= [#hex, var(--name), preset, or 'reset'] ; palette= [palette name to cycle per-glyph colors, or 'off'] ; field= [frame | background | text | title] ; padding= [border-to-content padding in pixels] ; top= [side pattern: `prefix(fill)suffix` or atomic] ; bottom= [side pattern: `prefix(fill)suffix` or atomic] ; left= [side pattern: `prefix(fill)suffix` or atomic] ; right= [side pattern: `prefix(fill)suffix` or atomic] ; tl= [single corner glyph (escapes apply)] ; tr= [single corner glyph (escapes apply)] ; bl= [single corner glyph (escapes apply)] ; br= [single corner glyph (escapes apply)]",
    "light [thin lines (default)] ; heavy [bold lines] ; double [double lines] ; rounded [thin lines with rounded corners] ; custom [user-supplied per-side / per-corner glyphs] ; cycle [advance to the next preset (wraps)]",
    "top ; bottom ; left ; right ; all",
    "reset [restore the slot's preset's default glyph]",
    "light [thin lines (default)] ; heavy [bold lines] ; double [double lines] ; rounded [thin lines with rounded corners] ; custom [user-supplied per-side / per-corner glyphs] ; cycle [advance to the next preset (wraps)]",
    "top ; bottom ; left ; right ; all",
    "reset [restore the slot's preset's default glyph]",
    "reset [restore the slot's preset's default glyph]",
    "from= ; to=",
    "arrow ; circle ; diamond ; none",
    "bg= [fill / background color] ; text= [text / label color] ; border= [frame / line color] ; section= [target section index inside a multi-section node] ; range= [grapheme range A..B inside the targeted section] ; pick ; picker",
    "accent ; edge ; fg ; reset",
    "on ; off",
    "section= [target section index inside a multi-section node]",
    "range= [grapheme range A..B inside the targeted section]",
    "-",
    "type= ; reset= ; display_mode=",
    "cross_link ; parent_child",
    "straight ; curve ; style ; position",
    "line ; portal",
    "set /set [pin the font family on the current selection] ; list [list every loaded font, each rendered in its face] ; size= [target on-screen size in points] ; min= [lower screen-space clamp in points] ; max= [upper screen-space clamp in points] ; section= [target section index inside a multi-section node] ; range= [grapheme range A..B inside the targeted section]",
    "set /set [pin the font family on the current selection] ; section= [target section index inside a multi-section node]",
    "10 ; 12 ; 14 ; 16 ; 18 ; 24 ; 32",
    "0 [\"Lord God\"] ; 1 [\"second\"]",
    "range= [grapheme range A..B inside the targeted section]",
    "-",
    "0 [\"Lord God\"] ; 1 [\"second\"]",
    "on ; off ; debug",
    "on ; off",
    "value=",
    "tight ; normal ; wide",
    "edit ; clear ; text= ; position= ; position_t= ; perpendicular=",
    "start ; middle ; end",
    "-",
    "default ; resize ; node-edit",
    "default",
    "list ; apply ; help ; inspect",
    "-",
    "-",
    "resize ; fit ; edit",
    "resize",
    "-",
    "-",
    "-",
    "move [shift section offset (dx/dy delta or x/y absolute)] ; resize [pin section size (w/h) or clear to fill-parent] ; show [print the resolved per-section properties] ; text [replace section text (runs=preserve|clear)] ; edit [open the section text editor on the resolved target] ; add [insert a new section] ; delete [remove the section (errors when only one remains)] ; split [split a section in two at a grapheme boundary] ; frame [configure the section's frame border (subverb tree)]",
    "move [shift section offset (dx/dy delta or x/y absolute)]",
    "dx= [relative move along x axis (canvas units)] ; dy= [relative move along y axis (canvas units)] ; x= [absolute x offset within parent node] ; y= [absolute y offset within parent node] ; section= [target section index inside a multi-section node]",
    "fill ; w= [section width (canvas units)] ; h= [section height (canvas units)] ; section= [target section index inside a multi-section node]",
    "text= [section text payload (quote multi-word values)] ; runs= [preserve|clear — keep or drop per-grapheme styling] ; section= [target section index inside a multi-section node]",
    "at= [insertion / split index] ; text= [section text payload (quote multi-word values)]",
    "at= [insertion / split index] ; section= [target section index inside a multi-section node]",
    "section= [target section index inside a multi-section node]",
    "section= [target section index inside a multi-section node]",
    "section= [target section index inside a multi-section node]",
    "0 [\"Lord God\"] ; 1 [\"second\"]",
    "preserve ; clear",
    "show ; reset ; preview ; preset= [light | heavy | double | rounded | custom] ; font= [font family for border glyphs (use `font list` for names)] ; size= [border glyph size in points] ; color= [#hex, var(--name), preset, or 'reset'] ; palette= [palette name to cycle per-glyph colors, or 'off'] ; field= [frame | background | text | title] ; padding= [border-to-content padding in pixels] ; top= [side pattern: `prefix(fill)suffix` or atomic] ; bottom= [side pattern: `prefix(fill)suffix` or atomic] ; left= [side pattern: `prefix(fill)suffix` or atomic] ; right= [side pattern: `prefix(fill)suffix` or atomic] ; tl= [single corner glyph (escapes apply)] ; tr= [single corner glyph (escapes apply)] ; bl= [single corner glyph (escapes apply)] ; br= [single corner glyph (escapes apply)] ; section= [target section index inside a multi-section node]",
    "light [thin lines (default)] ; heavy [bold lines] ; double [double lines] ; rounded [thin lines with rounded corners] ; custom [user-supplied per-side / per-corner glyphs] ; cycle [advance to the next preset (wraps)]",
    "commit [write the staged preview through and clear the slot] ; cancel [discard the staged preview, no model write] ; preset= [light | heavy | double | rounded | custom] ; font= [font family for border glyphs (use `font list` for names)] ; size= [border glyph size in points] ; color= [#hex, var(--name), preset, or 'reset'] ; palette= [palette name to cycle per-glyph colors, or 'off'] ; field= [frame | background | text | title] ; padding= [border-to-content padding in pixels] ; top= [side pattern: `prefix(fill)suffix` or atomic] ; bottom= [side pattern: `prefix(fill)suffix` or atomic] ; left= [side pattern: `prefix(fill)suffix` or atomic] ; right= [side pattern: `prefix(fill)suffix` or atomic] ; tl= [single corner glyph (escapes apply)] ; tr= [single corner glyph (escapes apply)] ; bl= [single corner glyph (escapes apply)] ; br= [single corner glyph (escapes apply)] ; section= [target section index inside a multi-section node]",
    "preset= [light | heavy | double | rounded | custom] ; font= [font family for border glyphs (use `font list` for names)] ; size= [border glyph size in points] ; color= [#hex, var(--name), preset, or 'reset'] ; palette= [palette name to cycle per-glyph colors, or 'off'] ; field= [frame | background | text | title] ; padding= [border-to-content padding in pixels] ; top= [side pattern: `prefix(fill)suffix` or atomic] ; bottom= [side pattern: `prefix(fill)suffix` or atomic] ; left= [side pattern: `prefix(fill)suffix` or atomic] ; right= [side pattern: `prefix(fill)suffix` or atomic] ; tl= [single corner glyph (escapes apply)] ; tr= [single corner glyph (escapes apply)] ; bl= [single corner glyph (escapes apply)] ; br= [single corner glyph (escapes apply)] ; section= [target section index inside a multi-section node]",
    "section= [target section index inside a multi-section node]",
    "0 [\"Lord God\"] ; 1 [\"second\"]",
    "0 [\"Lord God\"] ; 1 [\"second\"]",
    "clear ; min= [lower inclusive zoom bound (or `unset`)] ; max= [upper inclusive zoom bound (or `unset`)]",
    "clear",
    "unset ; 0.25 ; 0.5 ; 1.0 ; 1.5 ; 2.0 ; 3.0 ; 5.0",
    "unset ; 0.25 ; 0.5 ; 1.0 ; 1.5 ; 2.0 ; 3.0 ; 5.0",
];
