// SPDX-License-Identifier: MPL-2.0

//! Configurable keybindings.
//!
//! Hardcoded defaults overlaid with JSON: desktop reads
//! `--keybinds <path>` or `$XDG_CONFIG_HOME/mandala/keybinds.json`;
//! WASM reads `localStorage["mandala_keybinds"]` and nothing else.
//! There is **no `?keybinds=` layer** — the query-param machinery
//! exists in `crate::application::user_config::web_storage` and no
//! loader reaches it, because a query param is owned by whoever
//! composed the link rather than by the user; see
//! `KeybindConfig::load_for_web` for the full argument.
//! Failures log and skip the layer — the app never crashes for a bad
//! keybinds file. Partial configs work via serde's `default`
//! attribute, but only per *key*: a key whose value has the wrong
//! shape fails the whole parse and costs the user that entire layer
//! (issue #129).

mod action;
mod bind;
mod config;
mod context;
mod resolved;
mod surface;

#[cfg(not(target_arch = "wasm32"))]
mod platform_desktop;
#[cfg(target_arch = "wasm32")]
mod platform_web;

#[cfg(test)]
mod tests;

pub use action::Action;
// `ActionKind` is the variant-kind mirror of `Action` (no payloads),
// generated by strum's `EnumDiscriminants`. Used by the classifier
// methods (`is_destructive` / `context` / `wasm_compatibility`)
// because those classify by variant, not by payload, and by tests
// that need to iterate every variant via `ActionKind::iter()`.
#[allow(unused_imports)]
pub use action::ActionKind;
// Typed-payload enums for the parametric `SetColor` / `SetFont` /
// `SetZoom` Action variants. Re-exported so `cross_dispatch` and the
// `KeybindConfig` resolvers can name them without reaching into
// `keybinds::action`.
#[allow(unused_imports)]
pub use action::{BorderPreviewTargetKind, ColorAxis, FontSlot, ZoomBound};
// `WasmCompatibility` is consumed by `run_wasm/` (wasm32-only) and
// the test suite. On a native non-test build no caller pulls it in,
// hence the `unused_import` warning the lint would otherwise raise.
// Kept on the public surface so the wasm32 + test paths can find it
// uniformly; the allow reflects "no native production consumer today",
// not "spurious lint."
#[allow(unused_imports)]
pub use action::WasmCompatibility;
// The one mixed-branch set, shared by the dispatcher's WASM-macro
// lift and the classification test — see `MIXED_BRANCH_ACTIONS`.
pub(crate) use action::MIXED_BRANCH_ACTIONS;
// Public surface; the lint can't see in-crate test consumers without --tests.
#[allow(unused_imports)]
pub use bind::{key_to_name, normalize_key_name, KeyBind, MouseGesture};
pub use config::KeybindConfig;
pub use context::InputContext;
pub use resolved::ResolvedKeybinds;
// `ParametricBinding` is consumed by tests and by users authoring
// `keybinds.json` files (the JSON schema is the public surface);
// no in-binary native consumer pulls it in via `mandala::application::keybinds::ParametricBinding`,
// hence the lint exemption.
#[allow(unused_imports)]
pub use surface::ParametricBinding;
